### ISSUE TITLE
Allow passing `name` for `attach` without `mapParams/source`

### ISSUE THREAD

**Issue by NazariiShvets** [effector/effector#1000]
## Missing/Incorrect APIs
Can't pass `name` paramether in `attach` without `mapParams/source`

##  Suggested Implementation
https://github.com/effector/effector/blob/9d0f59af6f61e23d86b513041bc16b541c229063/packages/effector/index.d.ts#L2744

Current:
```ts
export function attach<
  FX extends Effect<any, any, any>,
>(config: {
  effect: FX
}): Effect<EffectParams<FX>, EffectResult<FX>, EffectError<FX>>
```
New: 
```ts
export function attach<
  FX extends Effect<any, any, any>,
>(config: {
  effect: FX,
  name?: string;
}): Effect<EffectParams<FX>, EffectResult<FX>, EffectError<FX>>
```

**Comment by zerobias** [comment]
Released in effector 23.2.3
