### ISSUE TITLE
Storing nodes in an effector store?

### ISSUE THREAD

**Issue by mkhoussid** [effector/effector#1026]
Suppose the following:

```javascript
. . .

const $inputRef = createStore();
const setInputRef = createEvent();
$inputRef.on(setInputRef, (_, node) => node)
. . .
const MyComponent = () => {
    . . .
    return (
        <input ref={(node) => setInputRef(node)} />
    );
}
```

Is this an anti-pattern in Effector? Seems to be [with Redux](https://stackoverflow.com/a/36919242/2891356)

**Comment by zerobias** [comment]
It's ok to store whatever you want in effector stores 👍 But I suggest to add [serialize: 'ignore'](https://effector.dev/en/api/effector/createstore/) to avoid serialization errors in tests or ssr
