### ISSUE TITLE
Question about DI

### ISSUE THREAD

**Issue by WoodenPC** [effector/effector#1046]
Hi, in redux we have thunk extra args middleware for DI. For example if we create some apiClient instance and pass it to extra args -> in some thunk getting that api client and making function calls. In mobx we can pass api client to store constructor. How i can achieve same logic in effector ?

**Comment by victordidenko** [comment]
Does this short article answer your question?
https://withease.pages.dev/magazine/dependency_injection.html

**Comment by WoodenPC** [comment]
@victordidenko it means that i need to attach some $apiClient store to every effect where i make api calls ?

**Comment by victordidenko** [comment]
Yes. Keep `apiClient` instance in some `$apiClient` store, and use effects to call its methods, like
```js
const methodFx = attach({
  source: $apiClient,
  effect: (apiClient, params) => apiClient?.method(params)
})
```

**Comment by victordidenko** [comment]
You can type your store like you want. If there is actually `null` in it, effect will fail in runtime, you can add reaction for `methodFx.fail` to handle such cases.
