### ISSUE TITLE
store.map() and lastState

### ISSUE THREAD

**Issue by DariaLitvinova** [effector/effector#1060]
There are information about arguments that receive `map` method [in documentation](https://effector.dev/en/api/effector/store/#methods-map-fn-arguments)

as I understand according to these PRs lastState was removed:
https://github.com/effector/effector/pull/1029
https://github.com/effector/effector/pull/846

But I didn't find such information in release notes or in docs
So please add this :)

**Comment by zerobias** [comment]
It is in changelog
> Remove deprecated second argument with state from $store.map ([PR #846](https://github.com/effector/effector/pull/846))

`lastState` in docs is an error, thanks 👍 It should be removed

**Comment by YanLobat** [comment]
Thank you for your attention to the details
