### ISSUE TITLE
Invalid types for `createEffect` and `attach` in factories with generics

### ISSUE THREAD

**Issue by kireevmp** [effector/effector#1069]
Invoking `attach` within factories with an unbounded type parameter causes an error when the `effect` in `attach` returns that type parameter.

![image](https://github.com/effector/effector/assets/29187880/71cce103-586d-42f6-9e07-e9f2d415e208)

https://github.com/effector/effector/blob/879134505b41e83896352c9930c326f9a1cf39aa/packages/effector/index.d.ts#L2813-L2815

Reproduction (with error and proposed fix): https://tsplay.dev/NdbxdW
The `Awaited` type I used is [available in TS](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-5.html#the-awaited-type-and-promise-improvements) since version 4.5

**Comment by zerobias** [comment]
Thanks  for report with suggested solution! This makes everything easier 👍 
We cannot use `Awaited` type directly until we introduce separate types for different versions, but we can cherry pick this type from typescript codebase
