### ISSUE TITLE
[effector-vue] Support two-way data binding in useUnit for Vue.js

### ISSUE THREAD

**Issue by 7iomka** [effector/effector#1107]
## Proposal

At the moment `useUnit` from `effector-vue/composition` has one-way data-binding, so, store becomes a read-only ref.
This makes it impossible to seamlessly use the store value in `v-model`.
This is kinda-ok for simple stores with primitive values or flat data structure, we can create a handler and instead of v-model we can use `value` + `@input` with created handler, passing value for primitive stores, or key + value for flat objects.
In the case of nested structures, we need extra effort to properly update the data in the handler, which is quite non-trivial, and at the same time forces us to write a boilerplate.

With **two-way data-binding support**, if we want to create or use any nested data (like json configs received from backend api)  as effector store, we don't need any extra steps (such as `smart event handler`) to make all the fields of this store work with v-model out of the box.
At the moment for each of this cases we need to create an additional `smart` event to handle nested updates correctly (especially when data structure is not typed).

There is a thought that it can be solved by an auto-created event which handle smart updates under the hood, or any other implementation if anyone has better ideas :)

## Use case

https://stackblitz.com/edit/vitejs-vite-87obv4?file=src%2FApp.vue

if we want to move settingsStore to the effector store (for ex.: $settings),  without two-way data binding we're going to get a lot of pain nowadays.

**Comment by igorkamyshev** [comment]
Can you use https://effector.dev/en/api/effector-vue/usevmodel/?
