### ISSUE TITLE
`scopeBind` should not throw, when called in safe context, even if threre is no scope

### ISSUE THREAD

**Issue by AlexandrHoroshih** [effector/effector#1123]
Currently, `scopeBind` will throw, if called outside of `scope` callstack and without `{ safe: true }` in its config.

It will throw even if `scopeBind` called in technically valid context, like from inside of an Effect, if Effect itself was called without scope

## Proposal

`scopeBind` should not throw at all, if called outside of `scope` callstack, but in a valid context (e.g. from an Effect)

## Use case

This code
```js
const historyUpdated = createEvent()
const subToHistoryFx = createEffect((history) => {
 const listener = scopeBind(historyUpdated)
 history.listen(listener)
})
```
should not throw at all, even if `subToHistoryFx` is called without `scope` and `scopeBind` does not have `{ safe: true }` set

This code
```js
// top-level
history.listen(scopeBind(historyUpdated))
```
should throw, as it would do now, since the call context itself is not valid

**Comment by zerobias** [comment]
Fixed in #1171
