### ISSUE TITLE
anchors in mobile docs cannot be copied

### ISSUE THREAD

**Issue by igorkamyshev** [effector/effector#1141]
🫡

**Comment by sergeysova** [comment]
It works. Where it cannot be copied?

**Comment by sergeysova** [comment]
All required anchors can be created using this basic structure: https://github.com/effector/effector/issues/1142

**Comment by igorkamyshev** [comment]
There https://effector.dev/en/typescript/typing-effector/

**Comment by igorkamyshev** [comment]
Now it's okay
