### ISSUE TITLE
Search index includes many pages "redirecting to..." and to desired page

### ISSUE THREAD

**Issue by igorkamyshev** [effector/effector#1143]
Search query — `typing effector`

Desired result — https://effector.dev/en/typescript/typing-effector/

Actual result 👇
<img width="1470" alt="Screenshot 2024-08-26 at 19 19 29" src="https://github.com/user-attachments/assets/ff860dfb-4aae-4266-83c8-d2ddc70a44f0">

**Comment by sergeysova** [comment]
<img width="1496" alt="image" src="https://github.com/user-attachments/assets/28d9cc0a-ffba-48b8-9d97-69bb2df0cf14">

Fixed in https://github.com/effector/effector/commit/558bc88e4ba7d7f00dc0562629b1d7831927c05d
