### ISSUE TITLE
Just throwing this out there

### ISSUE THREAD

**Issue by slikk66** [effector/effector#1148]
I used older effector with useStore and then there was this big update.  Honestly I can't really follow the main webpage, docs, examples, none of it.  I'm pretty proficient in development, have been doing this for a long time, but I literally can't wrap my head around this stuff.  Your first "simple example" on the examples page is this:

https://share.effector.dev/FnfBfWhN

This is not a simple example.  There's not much explanation at all.  So, I'll keep trying to figure it out, keep using it in the simple ways I have figured out so far, but I really think there is some serious over complication and lack of clarity in your messaging.

Flame away.

**Comment by YanLobat** [comment]
basically in terms of effector-react update
`useUnit` has shown up which includes both useEvent(which was used for SSR and was not need for SPA) and `useStore`,

Moreover it batches updates, so there should be only one useUnit for Component(`useUnit[$store, $store2]`) or in object form

Gate was around since older versions 

If you care to elaborate a bit more I would like to help you out

Because it is our common problem not only yours I guess. Little by little we are trying to improve docs

**Comment by slikk66** [comment]
Thanks for replying.  Yea, well I think that's part of the issue is know when to use what.  For me, most of the time I'm using a store for my main app state handling, and then I create functions inside the store that simply query an API and then run an "updateStore" function to deposit the data I've just received.

Every time I try to use more than one state, I get wrapped up in one store needing stuff from the other store, so I always go back to one store.  So that may be a topic to touch on.

Another aspect would be why there is a main difference between createEvent and createEffect.  I think there needs to be more explanation on why each of these things exist.  I get that Event has the state passed in, and is supposed to pass back out state, but you can also not pass out the state, and then it seems to work like an Effect?

I don't want to sound too negative, I have been using effector with good success.. mostly on the older version, but I feel like I'm only scratching the tip of the iceberg here with what it can do, and it's mainly because I just need someone to explain it at a high school level as opposed to a Astro Physics level, if that makes sense.  Lots of new concepts.

Example, on https://effector.dev/en/api/effector/effect/

````
import { type Effect } from "effector";

Effect is a container for async function or any throwing function.

It can be safely used in place of the original async function.
````

HUH?  Throwing function?  I don't even know that is.  Is that like a thrown error?  It's a container for functions that error?  It can be safely used in place of what original function?

Seems to me that should be something like:
"An Event represents something that happens in your app. You create it with createEvent.  Then you call it in your app for something like a button press.  Here's an example:"

Then it goes on to show an example:

````
import {createEffect} from 'effector';

const fetchUserReposFx = createEffect();

fetchUserReposFx.use(async (params) => {
  console.log("fetchUserReposFx called with", params);

  const url = `https://api.github.com/users/${params.name}/repos`;
  const req = await fetch(url);
  return req.json();
});

fetchUserReposFx({ name: "zerobias" });
// => fetchUserRepos called with {name: 'zerobias'}
````

OK, so this shows how to retrieve data using an Effect, and then.. does nothing with it?  I assume it gets returned back out from when you called it on the last line, but does it?  Is it meant to?  Is that the way to use it?  Would you then take that returned data and update your store with it using a Event?  Or does some other magic method like sample() the way to do that?

I guess just imagine someone coming to your site because a buddy said "hey, check out effector, it's cool".. I think in addition to this depth of technical knowledge and internal workings you have here there needs to be a "why Effector exists, our thinking process behind why it looks like it does, common use cases, sample mini-apps (eg. calendar, todo)" etc

**Comment by YanLobat** [comment]
As for elementary school kind of stuff, I did my best 4 years ago to perform a [quick enrollment ](https://dev.to/effector/effector-s-beginner-guide-3jl4) into effector. 

Quick notice forward and guard are outdated stuff now and all these things are covered by a sample which got filter field on top of the functionality it had 4 years ago

So the main difference between event and effect, the first successfully triggers **every** time, second one is needed for **any** side-effect(requests, timers, 3rd party API you are not sure about). The point is that effect **could** fail, 
so that's why event is just an event but effect is like a burger consists of 4 events (effect call itself, effect.done, effect.fail, effect.finally). Also, it has a shorthand `effect.doneData = effect.done.map({result}) => result`, and the same with failData

As for store composition `sample` is the main player out there, you could use it in a pretty flexible way like
```
sample({
source: {
first: $firstStore,
second: $secondGodDamnStuff
needToBeUpdatedInTheEnd: $guyWillDieFirst
},
clock: someCoolTriigerOccured, // it could effect.done, effect.fail etc
filter: ({second}) => second=== 'is a really tough stuff', //will pass further just if we got it really tough (could be store composition as well
fn: someBeautifulProcessingFnWhichWillCookThePayloadNotYourHead,
target: $guyWillDieFirst
})
```

Something like that, sorry for some bits of extra humor, don't take it personally it is just night time shift

**Comment by slikk66** [comment]
I'll read the link, thanks.  Gotta be honest I don't really follow your second half here at all.

Let me ask you something while I got you..

In my app right now, I have a modal.  On the action button I want the following 3 things to happen:

- call an asynchronous function just by name when the modal button is pressed: "let result = await addNewThingUsingDataFromInsideTheStore()" - I assume this will be an effect?
- that method will get some data from the current state, and use it to make an API post, then return the result of the post back to my calling button

So it's like a combination of an event (gets the state passed in) and effect (asynchronous post).. what is the right solution?

Appreciate your help, no worries about night shift humor 🥳

**Comment by YanLobat** [comment]
If you got you correct it would something like that

```
const openModal = createEvent()
const necessaryAsyncApiCallFx = createEffect(async(someGreatPayload) =>  await fetch(...blablala))
sample({
source: $storeYouNeed, // {or: $store1, store: $store2, shape: $store3}
clock: openModal,
fn: (sourcePayload, clockPayload) => ({...sourcePayload, ...clockPayload}) //implying just simple merge
target: necessaryAsyncApiCallFx
})
```

**Comment by YanLobat** [comment]
i'll give little bit implicit tip maybe

forget about using old school store.getState() kind of thing inside of thinks (in our case effects)
via sample we could orchestrate that shift pretty easily, for the first time it's mind-blowing I agree but the is worth the candle I promise

**Comment by slikk66** [comment]
I've got my issue working with your help!  Thank you!

This is just one small issue I was stuck on today, but I run into these things often.. this at least is something that I was able to get going now.  Your explanation and this page also helped: https://share.effector.dev/PAjWhOJc

So, now I can trigger the event inside my modal, but I can't get the value returned directly, I have to then pass it back to a call back, or I imagine pass in an Event as a parameter that can be called to store the returned value?

````
async () => {

const callback = (params: any) => {
   navigate(`/person/${params.id}`);
};

/* I would like to get the value returned from this, but this does not seem to be a function I can "await" it doesn't return anything, correct? */
doAddPersonFromModal(callback);

}
````

Here is my $store code:
````
/* PERSON ADD FROM MODAL  */
export const doAddPersonFromModal = createEvent<(params: any) => void>();
const executeAddPersonFromModal = createEffect();
executeAddPersonFromModal.use(async (params: any) => {
    let r = await doAddPerson({
        ...params.person,
    });
    params.callback(r);
});

sample({
    clock: doAddPersonFromModal,
    source: $store,
    fn: (store: Store, callback) => ({
        person: { ...store.heldPerson },
        callback,
    }),
    target: executeAddPersonaFromModal,
});
````

I do agree that this seems to be the way to go, I just need some more time to fully understand the ideas.  The link you sent from 4 years ago also had some good information.  I know it is not always fun to write things in a simplistic way, but I think this project could benefit from some more of it!  If I come to understand things further, I'd be happy to help with some examples/docs.

Thanks again!

**Comment by YanLobat** [comment]
navigate outside of the components code became side-effect as well, 
two options 
first is preferable - making an extra effect for navigation 
```
sample({
clock: doAddPersonFromModal, //called with params
target: navigateFx // it will receive params
})
```
 i don't know should be connected `executeAddPersonaFromModal` and `navigateFx` or not. So my proposal is just parallel execution

2-nd not not preferable and it is just `event.watch(params => navigate(/afda/params.id)`

**Comment by slikk66** [comment]
> const openModal = createEvent()
> const $resultStore = createStore(null)
> const necessaryAsyncApiCallFx = createEffect(async(someGreatPayload) =>  await fetch(...blablala))
> sample({
> source: $storeYouNeed, // {or: $store1, store: $store2, shape: $store3}
> clock: openModal,
> fn: (sourcePayload, clockPayload) => ({...sourcePayload, ...clockPayload}) //implying just simple merge
> target: necessaryAsyncApiCallFx
> })
> sample({
> clock: necessaryAsyncApiCallFx.doneData,
> target: $result
> })
> 
> //in your modal component
> 
> const result = useUnit($result)
> if (result === null) return null
> 
> ... some code if not null

Trying to follow this example, the $result I don't see being created.  That would be another Effect that I would create and import into my modal?

I tried this, but now I have: (store file)

````
/* PERSON ADD STUFF */
export const finshedAddPersonFromModal = createEffect();
export const doAddPersonFromModal = createEvent();

const executeAddPersonFromModal = createEffect(async (store: Store) => {
    let r = await doAddPerson({
        ...store.heldPerson,
        name: "New Person",
    });
    return {
        ...r,
        payload: "FROM EVENT",
    };
});
sample({
    clock: doAddPersonFromModal,
    source: $store,
    target: executeAddPersonFromModal,
});
sample({
    clock: executeAddPersonFromModal.doneData,
    target: finshedAddPersonFromModal,
});
````

And in my component with the modal I get error:
````
import Store, {
    doAddPersonFromModal,
    finshedAddPersonFromModal,
} from "../stores/Store";

function Persons() {
    const store = useUnit(Store);

    const result = useUnit(finshedAddPersonFromModal);

    if ( result ) {  /* ERROR -> this condition will always return true since this function is always defined.  Did you mean to call it instead? /*
        
    }
````

**Comment by YanLobat** [comment]
> Trying to follow this example, the $result I don't see being created. That would be another Effect that I would create and import into my modal?

I just did not write this code
yes it should const $result = createsStore(null) for instance

**Comment by YanLobat** [comment]
So hopefully issue was kind of resolved feel free to reopen just in case
