### ISSUE TITLE
attach types incorrect with name and effect params

### ISSUE THREAD

**Issue by Tsyklop** [effector/effector#1170]
Code: 

```
const userCreateLocalFx = attach({
  name: "userCreateLocalFx",
  effect: api.manage.user.createFx,
});
```

TS error:

![image](https://github.com/user-attachments/assets/228c88e0-009a-4198-8dab-12cea24e3f62)

effector: 23.2.2

**Comment by zerobias** [comment]
Fixed in effector 23.2.3
