### ISSUE TITLE
Best way to "split" the result of an effect into different directions

### ISSUE THREAD

**Issue by mkhoussid** [effector/effector#1176]
Suppose the following:

```javascript
const $user = createStore(null);
const $userPreferences = createStore(null);

const fetchUserInfo = createEffect(
	() => {
		return {
			user: { id: 1 },
			userPreferences: { darkMode: true },
		};
	},
);
```
Here is how I currently handle the `fetchUserInfo.doneData`:

```javascript
sample({
	clock: fetchUserInfo.doneData,
	fn: ({ user }) => user,
	target: $user,
});

sample({
	clock: fetchUserInfo.doneData,
	fn: ({ userPreferences }) => userPreferences,
	target: $userPreferences,
});
```

Is there a way to do this with another helper? I tried with `split`:

```javascript
const $user = createStore(null);
const setUser = createEvent();
$user.on(setUser, (_, { user }) => user);

const $userPreferences = createStore(null);
const setUserPreferences = createEvent();
$userPreferences.on(setUserPreferences, (_, { userPreferences }) => userPreferences);

split({
	source: fetchUserInfo.doneData,
	match: {
		user: ({ user }) => !!user,
		userPreferences: ({ userPreferences }) => !!userPreferences
	},
	cases: {
		user: setUser,
		userPreferences: setUserPreferences,
	},
});
```
But this doesn't decrease the amount of code — it does, however, increase the cognitive complexity.

Is sticking to the solution with `sample` my best bet here?

**Comment by YanLobat** [comment]
Feel free to write a helper function that will decrease the amount of code in your particular project
As for the library extension of `sample` operator - it is challenging for now in terms of proper type output

**Comment by YanLobat** [comment]
Oh I almost forgot about [spread](https://patronum.effector.dev/operators/spread/)

I guess this is what you're looking for

**Comment by mkhoussid** [comment]
I guess it is, but I'd rather create a helper as you've suggested, instead of installing a separate library for one use case. Thanks!
