### ISSUE TITLE
effector-vue lib does not export VueEffector from optionsApi.ts

### ISSUE THREAD

**Issue by egoson** [effector/effector#1178]
import { VueEffector } from 'effector-vue' - this is how it is imported for the second version

? – how to get VueEffector for vue 3?

there are suspicions that the export from optionsApi.ts does not get into the bundle

**Comment by zerobias** [comment]
Published in [effector-vue 23.1.0](https://github.com/effector/effector/releases/tag/effector-vue%4023.1.0)
