### ISSUE TITLE
Guide for SSR with effector

### ISSUE THREAD

**Issue by nschurmann** [effector/effector#203]
I'm planning on building an app that needs to be SEO friendly, do we have a guide to implement SSR with effector?

**Comment by sergeysova** [comment]
You can start from template: https://github.com/sergeysova/effector-ssr

**Comment by ilajosmanov** [comment]
https://github.com/ilajosmanov/vue-ssr-effector

**Comment by zerobias** [comment]
Now we have [server side rendering guide](https://effector.dev/en/guides/server-side-rendering/)
