### ISSUE TITLE
Cant pass tests when running from Windows

### ISSUE THREAD

**Issue by Wroud** [effector/effector#206]
It's look like this 
![Screenshot](https://sun9-46.userapi.com/c850732/v850732305/1b6d8a/YHd9_oUl4u4.jpg)

also path like this `/src/babel/__tests__/fixtures/create-component.js` on windows looks like this `\\\\\\\\src\\\\\\\\babel\\\\\\\\__tests__\\\\\\\\fixtures\\\\\\\\create-component.js`

Seems like this to occurs difference between snapshots

**Comment by zerobias** [comment]
Which tests are failed?

**Comment by abliarsar** [comment]
Can confirm, that typing part of tests does not work on Windows. Had the same issue with backslashes in paths

**Comment by Wroud** [comment]
1. Babel plugin - different sid's (somewhere with backslashes)
2. Tests related with babel plugin
3. Typings tests:
```
     - Snapshot
    + Received

    - 
    - --typescript--
    - Type '[number, "username" | "email" | "bio"]' is not assignable to type '[number, number]'.
    -   Type '"username" | "email" | "bio"' is not assignable to type 'number'.
    -     Type '"username"' is not assignable to type 'number'.
    - 
    + {global}
```

**Comment by zerobias** [comment]
Is it working now?

**Comment by Wroud** [comment]
Now most test is pass, but some still fail:
 FAIL   types  src/types/__tests__/effector/forward.test.js (7.789s)
<details>
  <summary>Click to expand</summary>
- Snapshot
    + Received

    @@ -1,10 +1,16 @@
      "
      --typescript--
    - Type 'Event<string>' is not assignable to type 'Unit<number>'.
    + No overload matches this call.
    +   Overload 1 of 2, '(opts: { from: Unit<string>; to: Unit<string>; }): Subscription', gave the following error.
    +     Type 'Event<number>' is not assignable to type 'Unit<string>'.
    +       Types of property '__' are incompatible.
    +         Type 'number' is not assignable to type 'string'.
    +   Overload 2 of 2, '(opts: { from: Unit<number>; to: Unit<number>; }): Subscription', gave the following error.
    -   Types of property '__' are incompatible.
    +     Type 'Event<string>' is not assignable to type 'Unit<number>'.
    +       Types of property '__' are incompatible.
    -     Type 'string' is not assignable to type 'number'.
    +         Type 'string' is not assignable to type 'number'.
</details>
 FAIL   effector/store  src/effector/store/__tests__/name.test.js 
<details>
  <summary>Click to expand</summary>
    Expected: "firstName"
    Received: "c"

    Expected: "combine(combine(firstName, lastName))"
    Received: "combine(combine(q, s))"
</details>
 FAIL   babel  src/babel/__tests__/raw-config.test.js
<details>
  <summary>Click to expand</summary>
    Expected: "foo"
    Received: "1"
</details>

**Comment by goodmind** [comment]
I think it should work now?

**Comment by Wroud** [comment]
Now tests related with babel-plugin fails with error:
`Cannot find module 'babel-plugin-.\src\babel\babel-plugin' from 'E:\!opensource\effector'`

**Comment by Wroud** [comment]
Today only one typings test fails:
` FAIL  src/types/__tests__/effector/forward.test.js (8.082s)`

**Comment by abliarsar** [comment]
That is probably because newer version of typescript. They added more detailed messages for overload errors in last version. Can you try running tests on  typescript 3.5.x? If they all pass, you can simply update dependency and failing snapshot.

**Comment by sergeysova** [comment]
Is this issue still actual?

**Comment by zerobias** [comment]
Closed due to inactivity, feel free to open new issue
