### ISSUE TITLE
Better documentation for `Store.map`

### ISSUE THREAD

**Issue by bloadvenro** [effector/effector#230]
> `map(fn: (state: State, lastState?: T) => T)`

We discussed this question a bit in community.

From my point of view `lastState` is not the best name for the second `fn` argument, because it actually contains NOT the last (previous as someone may think) state of current store, but __current state of a computed one.__ This is significant diffenece IMO and may discourage. Though it is pretty clear from typings (`lastState` has type `T`, not `State`), someone may experience cognitive dissonance :) 

What do you think about `map(fn: (state: State, lastComputedState?: T) => T)` and `map(fn: (state: State, lastComputedState: T) => T, initialComputedState: T)` ?

__Arguments section__

(-) `fn (Function)`: Function that receives `state` and `lastState?` and returns a new state for the derived store
(+) `fn (Function)`: Function that receives `state` and `lastComputedState?` and returns a new computed state for the derived store.
(+) `initialComputedState (T)`: Provide initial value for the `lastComputedState` argument (which has `undefined` value during the first store emission by default)  

__Examples__

I think, adding an additional simpe exampe in the manner of `const sumStore = numbersStore.map((n, sum) => sum + n, 0)` will be enough for people to understand the gist. This example shows similarity with reducer operation everyone already knows.

========================

Will be glad to receive feedback)

**Comment by zerobias** [comment]
Yes, sure, this looks reasonable 👍 

Also note that this is still a `map`, not `reduce`, so purpose of a second argument is to _use_ it in computations of a next value, not to accumulate it:
```js
function listQuery(source$, fn) {
  return source$.map(
    (list, prev) => compareLists(
      list.filter(fn), prev
    ),
    []
  )
}

function compareLists(a, b) {
  if (a.length !== b.length) return b
  for (let i = 0; i < a.length; i++)
    if (a[i] !== b[i]) return b
  return a
}```

Usage of computed state as an accumulator makes computations less manageable, as it prevent `.reset` on a parent store to be unambiguous and straightforward, so this should be noted in documentation, but how exactly? 🤔 

Also, could we split these cases in documentation entirely, to make difference more obvious?
```js
map(fn: (state: State) => T)
```
and
```js
map(fn: (state: State, lastComputedState: T) => T, initialComputedState)
```

**Comment by bloadvenro** [comment]
@zerobias I thought a lot about each thesis you provided and played with stores in repl.

> Also note that this is still a map, not reduce, so purpose of a second argument is to use it in computations of a next value, not to accumulate it

I propose to add "Caveats" section and strongly propose to consider usage of `Store.map` to accumulate values as an **antipattern**. I wrote an explanation in form of [some kind of story (in repl)](https://share.effector.dev/zhxN4106) with concise examples and commentaries which I plan to use as a basis in future PR.

**Comment by bloadvenro** [comment]
> Also, could we split these cases in documentation entirely, to make difference more obvious?

Sure, just give me some time to formulate :)

**Comment by bloadvenro** [comment]
As for

```js
map(fn: (state: State, lastComputedState: T) => T, initialComputedState)
```
Now I doubt that `initialComputedState` is a good name :)

Consider `storeA` and `storeB` (which is derived from `storeA`). As we already know, `lastComputedState` argument is `undefined` from the beginning, because `storeB` simply can't have any initial state value on its own (it has to be computed __inside__ the `.map` method of `storeA`).

What i want to say is explained in the code snippet below:

```js
const storeB = storeA.map(
  (state, lastComputedState) => state + lastComputedState,
  20 // So this is actually NOT the `initialComputedState`, it's more like a `seed`!
)

storeB.watch(console.log) // 30 <- THIS is the actual "initial computed state"
```

**Comment by zerobias** [comment]
@bloadvenro maybe we just can use `seed` as it is?

**Comment by bloadvenro** [comment]
@zerobias yeah, `seed` is the best candidate for now IMO

I will start to prepare a PR if you don't mind about the rest)

**Comment by zerobias** [comment]
@bloadvenro it would be great!

**Comment by egorguscha** [comment]
@bloadvenro is it still relevant?

**Comment by sergeysova** [comment]
@egorguscha Why you closed this issue?

**Comment by sergeysova** [comment]
Maybe we can rewrite issue description? Looks like a `store.map` still needs a better documentation at the moment.

**Comment by egorguscha** [comment]
Agree with you, let's reopen.

**Comment by sergeysova** [comment]
@egorguscha Great job!
