### ISSUE TITLE
[effector-vue] Intellisense not working properly on <template> with Vetur (VS Code), maybe because of effector's createComponent

### ISSUE THREAD

**Issue by maximelebreton** [effector/effector#246]
Hello!
When I use effector's **createComponent**,
```ts
import { createComponent } from "effector-vue"
```
In `<template>` tags, effector's variables shows an error (from Vetur):
![image](https://user-images.githubusercontent.com/1072425/68811083-0ea4b300-0670-11ea-9b51-0b871dbdee1d.png)
> Property '$user' does not exist on type 'CombinedVueInstance<Vue, object, object, object, Record<never, any>>

But in `<script>` tags, no problems
![image](https://user-images.githubusercontent.com/1072425/68811258-8377ed00-0670-11ea-89e4-acf21c5877d7.png)

```vue
<template>
    <div v-if="$users">{{$users}}</div>
</template>

<script lang="ts">
import { createComponent } from "effector-vue";
import { $users } from "./users";

const store = {
  $users
};

export default createComponent(
  {
    setup() {
      console.log($users)
    }
  },
  store
);
</script>
```

But on files that don't use effector, and so the vue composition-api **createComponent** is used, everything works as excepted in `<template>` tags:
```ts
import { createComponent } from "@vue/composition-api"
```

![image](https://user-images.githubusercontent.com/1072425/68811505-1a44a980-0671-11ea-9a42-b1e4d9bc2044.png)

So maybe it's a problem with effector's **createComponent** types?

Thanks!

____
You need to enable the Vetur experimental feature in VS Code extension settings:
![image](https://user-images.githubusercontent.com/1072425/68811197-5aeff300-0670-11ea-9797-0bf9f4f59e58.png)

**Comment by zerobias** [comment]
This is a relatively new feature, so there might be such issues

@ilajosmanov any ideas?

**Comment by ilajosmanov** [comment]
You can't use `createComponent` from effector with `vue-composition-api`.
We don't support unstable API ( like vue-composition-api ).
Our `createComponent` haven't `setup` method.

**Comment by ilajosmanov** [comment]
And yes, I didn't know about experimental feature in Vetur )

**Comment by sergeysova** [comment]
@ilajosmanov @maximelebreton Is this issue still actual?

**Comment by ilajosmanov** [comment]
could be closed.
