### ISSUE TITLE
remap should infer type without "as const"

### ISSUE THREAD

**Issue by zerobias** [effector/effector#307]
**Current behavior:**

In case with array of keys, `remap` merges their types

```typescript
const store = createStore({foo: '', bar: 0})
const [foo, bar]: Store<string | number> = remap(store, ['foo', 'bar'])
```

```
Type 'Store<string | number>[]' is missing the following properties from type '[Store<string>, Store<number>]': 0, 1
```

**Reproduction:**

Reproduction is shown in [type tests](https://github.com/zerobias/effector/blob/master/src/types/__tests__/effector-dom/index.test.ts#L121) for `remap`.

[_Type tests in our contribution guide_](https://github.com/zerobias/effector/blob/master/CONTRIBUTING.md#type-tests)

**Expected behavior:**

Each store should have its own type

```typescript
const store = createStore({foo: '', bar: 0})
const [foo, bar]: [Store<string>, Store<number>] = remap(store, ['foo', 'bar'])
```

**Comment by sergeysova** [comment]
Is it still actual?

**Comment by cinic** [comment]
@sergeysova i think it's not actual now.
<img width="397" alt="Screenshot 2021-12-09 at 10 28 01" src="https://user-images.githubusercontent.com/67061/145352789-de684562-f4b9-4e38-a47f-21ca721028db.png">
