### ISSUE TITLE
How to properly mock store

### ISSUE THREAD

**Issue by pbelyaev** [effector/effector#370]
Hello everyone.

I'm trying to get the best possible way to mock a store in unit tests. I came up with a simple way to just mock `getState` method but I think there is a better solution floating around. 

I have a simple `CounterComponent`:
```tsx
import counter from 'stores/counter';
import { useStore } from 'effector-react';

export default function CounterComponent() {
  const counter = useStore(counter);

  return (
    <h1>Current counter: {counter}</h1>
  );
}
```

And I want to unit test it and check that it's displaying value from the store but I don't want to test the store itself. So I came up with this:

```ts
import counter from 'stores/counter'

jest.mock('stores/counter', () => {
  const actualObject = jest.requireActual('stores/counter');

  return {
    ...actualObject,
    getState: jest.fn()
  }
})

describe('CounterComponent Unit', () => {
  it('should display counter from counter store', () => {
    counter.getState.mockReturnValueOnce(0)

    // just to make it shorter I skipped rendering and finding part of the test,
    // imagine that this is the result of testing-library or any other library
    const textContent = 0

    expect(textContent).toBe(0)
  });
});
```

How do you unit test in this case? Any suggestions?

**Comment by zerobias** [comment]
I published an [article about testing with effector](https://www.patreon.com/posts/testing-api-with-32415095)

In short, you can use separate event to set store value before and reset it back after test

```js
import {createEvent} from 'effector'
import {apiRequestFX, lastResults} from '../app'
let currentHandler
beforeEach(() => {
  currentHandler = apiRequestFX.use.getCurrent()
})
afterEach(() => {
 apiRequestFX.use(currentHandler)
})
const resetResults = createEvent()
beforeAll(() => {
  lastResults.reset(resetResults)
})
afterAll(() => {
  lastResults.off(resetResults)
})
test('api requests will be added to the end of lastResults list', async() => {
  resetResults()
  apiRequestFX.use(() => 'api response')
  await apiRequestFX()
  expect(lastResults.getState()).toEqual(['api response'])
  apiRequestFX.use(() => 'last update')
  await apiRequestFX()
  expect(lastResults.getState()).toEqual(['api response', 'last update'])
})
```

**Comment by pbelyaev** [comment]
This is interesting, thanks. But I'm looking for something that would not require to execute any effects or events. For example for components that just use store and never call any effects or events. 

Long story short, something that you can call and mock what's inside the store.

**Comment by amandafsilva** [comment]
@pbelyaev Not sure this is exactly what you asked, but in my tests I usually do it like this:

```
import * as effector from 'effector-react';

const useStoreMock = jest.spyOn(effector, 'useStore');

useStoreMock.mockReturnValue(0);
```

**Comment by pbelyaev** [comment]
@amandafsilva great, that's is closer to what I am looking for. Thank you. I have a question though - what if there are more than one `useStore` hooks used? How do you return a value for each one of them?

**Comment by amandafsilva** [comment]
@pbelyaev with other hooks I managed to do that by chaining `mockReturnValueOnce`, I guess with `useStore` should work as well. So it'd be something like:

`useStoreMock.mockReturnValueOnce(0).mockReturnValueOnce(1);`

**Comment by pbelyaev** [comment]
@amandafsilva hm, seems unstable. If there will be added a new `useStore` hook on the top of the component then test will fail. Unfortunately, jest mocking can not return value based on arguments (there is an issue regarding this feature https://github.com/facebook/jest/issues/6180) so the only way around is to mock actual implementation of `useStore` and check passed arguments returning value accordingly.

Anyway, thank you for this approach, I didn't think about mocking the hooks itself.

**Comment by amandafsilva** [comment]
@pbelyaev no problem :) and yeah, it's not a pretty solution, but using chained `mockReturnValueOnce/mockImplementationOnce` was the only way I found in the jest docs to return different values to multiple calls of a funcion. 

I just didn't understand why the test would fail if there was another `useStore`, though...

**Comment by pbelyaev** [comment]
@amandafsilva well imagine you have a component like this:

```jsx
const NewNotificationsAlert = () => {
  const username = useStore($userName)
  const notificationsCount = useStore($notificationsCount)

  return (
    <p>Hello, {username}! You have {notificationsCount} new notification(s).</p>
  )
}
```

Test will have a mock like this:
```js
useStoreMock.mockReturnValueOnce('John Doe').mockReturnValueOnce(10);
```

But then someone adds a new `useStore` hook at the top of the component:
```jsx
const NewNotificationsAlert = () => {
  const importantNotificationsCount = useStore($importantNotificationCount)
  const username = useStore($userName)
  const notificationsCount = useStore($notificationsCount)

  return (
    <>
      <p>Hello, {username}! You have {notificationsCount} new notification(s).</p>
      <p>{importantNotificationsCount} of them are/is important.</p>
    </>
  )
}
```

Now previous test that probably expected some values to be displayed will fail because instead of 

```
"Hello, John Doe! You have 10 new notification(s)."
``` 

it will show:

```
"Hello, 10! You have undefined notification(s)."
```

**Comment by amandafsilva** [comment]
@pbelyaev oh, right! Yeah, in this case, for every new `useStore` call, we'd have to add a new `mockReturnValueOnce` in the correct order:

`useStoreMock.mockReturnValueOnce(2).mockReturnValueOnce('John Doe').mockReturnValueOnce(10);`

`"Hello, John Doe! You have 10 new notification(s). 2 of them are/is important."`

I did a quick research and the last answer on [here](https://stackoverflow.com/questions/57025753/how-to-set-initial-state-for-usestate-hook-in-jest-and-enzyme) shows a way of mocking two `useState`, maybe it could work for `useStore` as well.

**Comment by danielnakamashi** [comment]
If you didn't find a better solution, I have a suggestion.
```javascript
import counter from 'stores/counter';

jest.mock('stores/counter', () => {
  const { createStore } = jest.requireActual('effector');
  return createStore(30);
});

describe('CounterComponent Unit', () => {
  it('should display counter from counter store', () => {
    expect(counter.getState()).toBe(30);
  });
});
```
