### ISSUE TITLE
How to use effector with Vue 3 & composition API

### ISSUE THREAD

**Issue by vanniewelt** [effector/effector#381]
Hello, I came across Effector few days ago. I really like its approach to state management and I'd like to use it in my Vue 3 application I'm currently working on. However, it seems that Effector does not support composition API. Can be composition API support expected anytime soon? Is there any way to make Effector work with composition API now?

I have seen [this comment that you don't support composition API](https://github.com/zerobias/effector/issues/246#issuecomment-554912664) since it wasn't stable then. Now I think we can be pretty confident that there won't be any breaking changes as Vue 3 is RC now.

**Comment by zerobias** [comment]
The main issue with composition api is that it require to import new methods to work, which unavailable in vue 2. Although @vue/composition-api could help, is it possible to introduce it transparently to users which are not using composition api yet?

**Comment by zerobias** [comment]
> Is there any way to make Effector work with composition API now?

This should work:

```js
import {shallowRef, readonly, onMounted, onUnmounted} from 'vue'

export function useStore(store) {
  const ref = shallowRef(store.getState())
  let unwatch
  onMounted(() => {
     unwatch = store.watch(value => {
      ref.value = value
    })
  })
  onUnmounted(() => {
    unwatch()
  })
  return readonly(ref)
}
```

**Comment by yogurt1** [comment]
shallow-ref for Vue2 Composition API plugin
```
import { Ref, ref, computed } from '@vue/composition-api';

export function shallowRef<T>(initialValue: T): Ref<T> {
  let value = initialValue;
  const updateRef = ref(0);

  return computed({
    get() {
      updateRef.value;
      return value;
    },
    set(newValue: T) {
      value = newValue;
      updateRef.value = Math.floor(Math.random() * 1000);
    },
  });
}
```

**Comment by yogurt1** [comment]
I using this in Vue2 + Composition API plugin + TypeScript project
shallowRef defined in [this comment](https://github.com/zerobias/effector/issues/381#issuecomment-693602367)

```typescript
export function useStore<State>(store: Store<State>): ReadonlyRef<State> {
  const stateRef = shallowRef<State>(store.getState());

  const unwatch = store.watch(state => {
    stateRef.value = state;
  });

  onUnmounted(unwatch);

  return stateRef;
}
```

**Comment by YanLobat** [comment]
@vanniewelt Good news! effector-vue 21.1.0 is out! And it supports Vue 3

Hooks API

• useStore (https://effector.dev/docs/api/effector-vue/useStore) — for render data (can’t mutate in vue components, only via effector events)
• useVModel (https://effector.dev/docs/api/effector-vue/useVModel) — for render data and also provide functionality mutating via v-model

Gate API

• createGate (https://effector.dev/docs/api/effector-vue/createGate) — Gate is a hook for conditional rendering, based on current value (or values) in props. An example of a problem that Gate can solve - you can put together all required data, when component was mounted.
• useGate (https://effector.dev/docs/api/effector-vue/useGate)  — hook which pass data to GateComponent when component mounted and unmounted

**Comment by zerobias** [comment]
I think now this issue is successfully resolved. Feel free to open another one if we missed something

**Comment by vanniewelt** [comment]
Oh, sorry for not responding. This is awesome progress, thanks!
