### ISSUE TITLE
Lazy calculations

### ISSUE THREAD

**Issue by PFight** [effector/effector#416]
How to organize lazy calculation of value with effector? 

For example, I have store A, and sometime will need value B, that calculated from A with some expensive operation. Value B will be needed only at certain conditions (on button click, for example), so I do not want to calculate it immidietly after A has been calculated. How to define store B?

**Comment by i1yas** [comment]
If you need B to be store, then:
```
const B = createStore(null);
const buttonClicked = createEvent();

sample({
  source: A,
  clock: buttonClicked,
  target: B,
  fn: someExpensiveOperation
})
```
[Repl](https://share.effector.dev/7JftBNoM)
