### ISSUE TITLE
clearNode on domain breaks effect

### ISSUE THREAD

**Issue by thecotne** [effector/effector#421]
**What is the current behavior:**

when i call clearNode on domain, effect that is defined outside this domain is broken and does not fire events

**Please provide the steps to reproduce and if possible a minimal demo of the problem via https://share.effector.dev, https://codesandbox.io or similar**

https://share.effector.dev/M62Nbfho

**What is the expected behavior:**

clearNode on domain should erase stuff inside domain and should not affect other domains and stuff defined outside the domain

**Which versions of effector packages, and which browser and OS are affected by this issue? Did this work in previous versions of effector?:**  

effector 21.7.0 (but issue exists in older versions as well)

**Comment by zerobias** [comment]
Fixed in `effector 21.7.1`
