### ISSUE TITLE
Standartize `fx.finally` like in `allSettled`

### ISSUE THREAD

**Issue by sergeysova** [effector/effector#427]
## Proposal

Add field `value` for `.finally` when status is `"fail"`. New field should be an alias for `error`.

1. be consistent with the [`allSettled`](https://effector.dev/docs/api/effector/allSettled)
1. have the same shape as with status `"done"`

_Do not remove `error` property_

## Use case

1. Simple destructuring

```ts
const result = fx.finally.map(({ value }) => value)
// doesn't matter "fail" or "done", just give me a value
```
compare with:

```ts
const result = fx.finally.map((data) => data.status === 'fail' ? data.error : data.value )
```

**Comment by victordidenko** [comment]
```javascript
const result = fx.finally.map(({ error, value }) => error ?? value)
```

**Comment by zerobias** [comment]
> ```js
> const result = fx.finally.map(({ error, value }) => error ?? value)
> ```

The goal is to avoid such handwritten unification

**Comment by zerobias** [comment]
I wonder if this affects types in existing projects?

Also, I'm think effector-reeffect should be updated to

**Comment by victordidenko** [comment]
I just don't get the point, what is the practical sense in that?

> // doesn't matter "fail" or "done", just give me a value

When doesn't this matter, in which practical case?

**Comment by zerobias** [comment]
[Issue with current approach](https://www.typescriptlang.org/play?#code/FASwtgDg9gTgLgAgN4GMYFMCGd0FEBm+6KcAvgvjFGAgOTqHFyy3DApQB2AzovgB4IAvAjRYcBIiQA8ANyggAJgBoEvGCE4BzVZwCuYAEboYAPgAUASjYCAdPk2YANk4CetgO7YUAC3PmkXmw9blVZZz10VRMqGFJLYVNkYAQEEHwEcyC4EOEhEVpFLnRaBKQU1NEubigndFsnKC1zcKdI61TSYHjgIA):

```typescript

import {createEffect} from 'effector'

const fx = createEffect<void, string, number>()

fx.finally.watch(({status, value, error}) => {
  if (status === 'done') {
    console.log(value)
  }
})

```

Neither `value` nor `error` could be accessed before `status` check

**Comment by victordidenko** [comment]
It occurs to me, that there is no `value` in fx.finally, so we are talking about `result`?
Or about adding new field `value` into done and fail both? Where `value = result` in case of success, and `value = error` in case of failure?

**Comment by zerobias** [comment]
Oh, yes, sure, just typo

**Comment by victordidenko** [comment]
Type narrowing will not work with argument destructuring anyways:
<img width="348" alt="Screenshot 2020-11-22 at 19 48 51" src="https://user-images.githubusercontent.com/15016227/99909880-13c52500-2cfc-11eb-98d2-7903fe72d179.png">
But **will work** without destructuring, so, in my opinion, not a big deal, if you care about typings issues in that proposal...
<img width="366" alt="Screenshot 2020-11-22 at 19 49 56" src="https://user-images.githubusercontent.com/15016227/99909914-41aa6980-2cfc-11eb-86a1-494b5b43477a.png">

**Comment by zerobias** [comment]
Hm, yes, you're right 🤔 Then that rfc might yield more issues than benefits

**Comment by sergeysova** [comment]
Ok. Closing it
