### ISSUE TITLE
Add custom store comparer option

### ISSUE THREAD

**Issue by PFight** [effector/effector#428]
## Proposal

Add option to createStore method, that will change comparision logic of the store value. Docs says:

> Store is updated when it receives a value that is not equal (!==) to current one and to undefined

But sometimes it not convinient to use only reference comparision, but there is need to add some deep comparision.

## Use case

I have a simple struct { x, y }. I need to operate with these two values simulatenously, i.e. set bot values simulatenously, and notify listeners when boths values updated. Ofcourse, I can create 3 store - $x, $y, and combine it to $point. But I do not need to process x and y separately and do not need to notify separately for changes of x, and changes of y, so creating 3 stores instead of one is syntax overhead (I will need to create also 2x dublicting events). That's why I preffer create single store $point with complex object { x, y }, but then, I got need to write code like this to prevent :

```js
function setPoint(x, y) {
    let oldState = $point.getState();
    if (oldState.x !=x && oldState.y != y) {
         setPointEvent({ x,  y});
    }
}
```

Or also code like this: `setPointEvent(...point);`

 It's quite awfull.

**Comment by zerobias** [comment]
Just return undefined if you don’t need to update store

```js
const move = createEvent()
const position = createStore({x: 0, y: 0})
  .on(move, (position, {x, y}) => {
    if (position.x !== x && position.y !== y) {
      return {x, y}
    }
  })
```

**Comment by zerobias** [comment]
I was going to suggest you to merge events to apply them at once, but maybe your suggestion really make sense. Thus we need to understand how it should looks like.

The term "store comparator" looks like it something about comparisons between stores, but it more an "update filter".

Then it might look like that:

```js
const position = createStore({x: 0, y: 0}, {
  updateFilter: (update, current) => update.x !== current.x
})

position.on(move, (_, upd) => upd)

move({x: 0, y: 0})
// no reaction
move({x: 1, y: 2})
// position → {x: 1, y: 2}
```

1. `move` called
2. `position` update
    1) check if update from `move` is not `undefined`
    2) `updateFilter` called with `move` payload and current `position` state
    3) if `updateFilter` return truthy value, then update `position` with `move` payload

**Comment by PFight** [comment]
The another case:

```
let point = { x: 1, y: 1 };
move(point); // position -> { x: 1, y: 1 }
point.x += 1;
move(point); // reference is the same, but because of updateFilter change detected, and position -> { x: 2, y: 2 }
```

**Comment by zerobias** [comment]
Store values should be immutable, mutations are not supported. Even more, in this case `updateFilter` will return false, as you'll compare an object with itself

**Comment by victordidenko** [comment]
Doesn't this solved by mapped store?

- You don't process `x` and `y` separately
- You will not create 2 dublicting events
- You will write condition just once

```js
const move = createEvent()

const $prepoint = createStore({ x: 0, y: 0 })
  .on(move, (_, curr) => curr)

const $point = $prepoint.map(
  (curr, prev) =>
    !prev || curr.x !== prev.x && curr.y !== prev.y
      ? curr
      : prev
)

$point.watch(_ => console.log('$point.watch:', _))

move({ x: 0, y: 1 })
move({ x: 1, y: 0 })
move({ x: 1, y: 1 })
```
will ouptut
```
$point.watch: {x: 0, y: 0}
$point.watch: {x: 1, y: 1}
```
