### ISSUE TITLE
Store.watch is not triggered.

### ISSUE THREAD

**Issue by Auxxxxlx** [effector/effector#436]
https://share.effector.dev/cAqtkdF8

```javascript
import {createStore, createApi} from 'effector'

const playerPosition = createStore({
  left: 1,
  right: 1.2,
})

// create events and attach them to store
const api = createApi(playerPosition, {
  moveLeft: (pos, n) => {
    pos.left = n
    return pos
  },
  moveRight: (pos, n) => {
    pos.right = n
    return pos
  },
})

playerPosition.watch(pos => {
  console.log('position', pos)
})
// => position 0

api.moveRight(10)
// => position 10
api.moveLeft(5)
// => position 5

console.log(playerPosition.getState())
```

<img width="495" alt="截屏2020-12-26 06 11 34" src="https://user-images.githubusercontent.com/13865581/103142631-3904e300-4741-11eb-8348-077e6174b352.png">

**Comment by egorguscha** [comment]
It doesn't work because you return the same object. You should update the reference to an object.
```js
const api = createApi(playerPosition, {
  moveLeft: (pos, n) => {
    pos = {...pos}
    pos.left = n
    return pos
  },
  moveRight: (pos, n) => {
    pos = {...pos}
    pos.right = n
    return pos
  },
})
```

**Comment by doasync** [comment]
The value in the store is not the object itself, but a reference to it. You mutate the object, but return the same reference, so there is no update and the store is not triggered. 

The documentation says: 
"Store is updated when it receives a value that is not equal (!==) to current one and to undefined"
https://effector.dev/docs/api/effector/store/

Read more about object references:
https://javascript.info/object-copy

**Comment by Auxxxxlx** [comment]
I have transfer to vuex. Maybe we could make the Store object reactive through proxy, just like vue3 reactivity.

**Comment by zerobias** [comment]
Effector works with **multiply** stores, not a single one, you **do not** need to mutate at all because your stores are atomic:

```js
const moveLeft = createEvent()
const moveRight = createEvent()

const playerPositionLeft = restore(moveLeft, 1)
const playerPositionRight = restore(moveRight, 1.2)

const playerPosition = combine({left: playerPositionLeft, right: playerPositionRight})
```

If mutability is absolutely critical for you then you should have told about this at very beginning, we are not mind readers yet

**Comment by doasync** [comment]
If you are going to store an object and modify some parts of it, you will probably need to decompose such an object. Extract the parts you plan to modify into separate stores so that you can work with them atomically:

```ts
const profile = {
      name: 'Joe',
      isLogged: true,
      balance: 99,
}

const $name = createStore(');
const $isLogged = createStore(false);
const $balance = createStore(0);
```

Atomic stores are easier to update, combine, and calculate derived data from. There is no need to write selectors and memoize them. Data is normalized and redundancy is eliminated by creating computed stores. By skipping unnecessary updates (in stores) and batching, efficiency is increased.

If you need to create a store with an object whose fields will contain values from other stores, use the *combine* function:

```ts
const $profile = combine({
    name: $name,
    isLogged: isLogged,
    balance: $balance,
})
```
