### ISSUE TITLE
Clear scope?

### ISSUE THREAD

**Issue by darky** [effector/effector#440]
Hello! I want to use **Effector** with Node.js
Need to fork domain into scope on each request -> do some stuff with scope -> clear scope, when request finished.

But how to clear scope? I found `clearNode` util, but it's not work with scope...

**Comment by zerobias** [comment]
Scopes are not connected to anything (no references to scope anywhere), so you doesn’t need to call clearNode with them
But even if you want to be explicit, clearNode indeed [support scopes](https://share.effector.dev/MJnUBVIk)
Looks like the only thing that is wrong is lack of Scope in clearNode typings and documentation

**Comment by darky** [comment]
Thanks!

**Comment by darky** [comment]
> Scopes are not connected to anything (no references to scope anywhere)

@zerobias, you mean that scopes will be garbage collected?

**Comment by zerobias** [comment]
@darky yes, they are
