### ISSUE TITLE
createAPI broken types

### ISSUE THREAD

**Issue by binjospookie** [effector/effector#468]
**What is the current behavior:**

TypeScript errors when I try to return undefined from the event created with createApi.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via https://share.effector.dev, https://codesandbox.io or similar**

https://codesandbox.io/s/focused-bird-zke04?file=/src/index.ts

**What is the expected behavior:**

No TypeScript error :) 

**Which versions of effector packages, and which browser and OS are affected by this issue? Did this work in previous 
versions of effector?:**

effector@21.8.8

**Comment by zerobias** [comment]
fixed in `effector@21.8.9`

**Comment by binjospookie** [comment]
Cool!
