### ISSUE TITLE
useStoreMap should have fn predefined

### ISSUE THREAD

**Issue by lkostrowski** [effector/effector#475]
## Proposal

`useStoreMap` requires (at least in typings) `fn` to be provided.

However, IMO `fn` should not be mandatory and have identity function as default (`state => state`)

## Use case

I create my effector state inside some class/module where I already keep my mapping functions (you can call them something like redux selectors)

Then I need to use it in UI

```
const zoneID = props.match.zoneID; // take from router

const zone = useStoreMap({
  store: zoneStore.getZoneByID(match.params.zoneID), // zoneStore contains my domain etc
  keys: [match.params.zoneID],
  fn: (state) => state, // <- not required, mapping happens in another layer
});

```

**Comment by zerobias** [comment]
If you doesn’t need `fn` then this is a case for [useStore](https://effector.dev/docs/api/effector-react/useStore)
If you need to pass data from props to store you could use [useGate](https://effector.dev/docs/api/effector-react/useGate)

The key is that you don’t need to do complex computations in view

**Comment by lkostrowski** [comment]
Thanks for answer. 
As you mentioned, I need to pass props, so `useStore` is no-go.

Gate is interesting concept, I will eventually use it, but it seems to be quite strange API. Maybe its my bias coming from redux+selector approach, but it more natural for me to use `useStoreMap` like in example.

Maybe can you provide some more real-life example of using gates so I can build some mental model around it?

**Comment by zerobias** [comment]
[Gate - a bridge between props and store](https://effector.dev/docs/recipes/react/gate)
