### ISSUE TITLE
﻿﻿﻿﻿Strange order of calls

### ISSUE THREAD

**Issue by binjospookie** [effector/effector#478]
**What is the current behavior:**
Call order: 
* first evt
* second evt
* second target
* first target

**Please provide the steps to reproduce and if possible a minimal demo of the problem via https://share.effector.dev, https://codesandbox.io or similar**

https://codesandbox.io/s/affectionate-snyder-s5zu3?file=/src/index.ts

**What is the expected behavior:**
Call order: 
* first evt
* second evt
* first target
* second target

**Which versions of effector packages, and which browser and OS are affected by this issue? Did this work in previous versions of effector?:**

effector@21.8.11

**Comment by i1yas** [comment]
```
forward({
  from: rootEvt,
  to: [firstEvt, secondEvt]
});
```
This expression does not guarantee order of calls. Both events would be triggered with rootEvt params and that's all. Order depends on other things.

In index.js you have imports
```
import { secondEvt } from "./second";
import { firstEvt } from "./first";
``` 
So secondEvt subscribed to updates first, and then firstEvt subscribed
```
secondEvt.watch(...);
firstEvnt.watch(...);
``` 
But I don't recommend to rely on such things like module imports order, etc.

If you really need strict order of calls, then you must describe it explicitly
```
forward({
  from: rootEvt,
  to: firstEvt
})
forward({
  from: firstEvt,
  to: secondEvt
})
```

**Comment by binjospookie** [comment]
> So secondEvt subscribed to updates first, and then firstEvt subscribed

It's not safe. Because it's possible to change app behavior with imports order changing.

> If you really need strict order of calls, then you must describe it explicitly

The reason for firstEvt firing does not always depend on rootEvt. And we shouldn't call secondEvt on each firstEvt firing.

**Comment by binjospookie** [comment]
Example

```
forward({
  from: guard({
    source: sample({
      clock: someFx.doneData,
      fn: (result) => (isCorrect(result) ? result.data : null),
    }),
    filter: (payload): payload is Correct => !isNil(payload),
  }),
  to: [update([data]), select({ id: data.id })]
});
```

`update` just update list
`select` checks that data in list and select if true

**Comment by doasync** [comment]
It seems like all events in `to` array are fired at once. I'm not sure if it is a bug. 

The order is going to be correct if you use separate `forward` for each `to` event:

```ts
forward({ from: rootEvt, to: firstEvt })
forward({ from: rootEvt, to: secondEvt })
```

**Comment by binjospookie** [comment]
Events call order is correct.
Targets call (first, second) is not.

Splitting on two forwards [doesn't help](https://codesandbox.io/s/priceless-fermi-bpimg?file=/src/index.ts). Order still depends on imports order.

**Comment by zerobias** [comment]
You might move all side effects to [init files](https://effector.dev/docs/conventions/best-practices#file-structure) and import them in root init

**Comment by zerobias** [comment]
Guards and samples always executed in order of definition. You might pass `greedy: true`, to avoid that behavior, but this is strong sign that your code is not clear and rely on weak assumption. Usually, you need to separate data reading from data writing, but unfortunately, your example in codesandbox isn't show anything, as console logs aren't business logic so I cant show you how you can act

**Comment by binjospookie** [comment]
I apologize for the long response.

Yes, you're right. It looks like poorly designed system.
