### ISSUE TITLE
useStore doesn't react to store changes under certain conditions

### ISSUE THREAD

**Issue by nsf** [effector/effector#481]
**What is the current behavior:**

Under certain conditions when store value passed to "useStore" changes, it causes a desync between reducer that is defined inside that function and the store itself. Which causes unexpected lack of reaction to store changes in UI.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via https://share.effector.dev, https://codesandbox.io or similar**

Demo with proposed solutions: https://share.effector.dev/zVuVJYiq

In short: click "toggle" once (any of them), click "reset" once, click "toggle" once. You'll see that "useStore" version didn't react to last change.

I added what I think might fix the issue, but I'm not a react expert. In theory "effector" already dedupes redundant changes and as long as something forces react to re-render on ".updates.watch()" callback invocations it should work correctly.

**What is the expected behavior:**

"useStore" should always cause UI to react to store changes.

**Which versions of effector packages, and which browser and OS are affected by this issue? Did this work in previous versions of effector?:**

Haven't checked it on any other versions. True for current release 21.8.11 version and for master (0c836cd0ac974f91eabe44b88fd1639dad555ab7).

**Comment by zerobias** [comment]
You should not create stores from react at all, effector is not a fancy useState replacement. Could you show an example without store recreation?

**Comment by zerobias** [comment]
And indeed, unnecessarily rerenders are serious issues

**Comment by nsf** [comment]
>You should not create stores from react at all

>an example without store recreation

Both of these are not part of the bug. 

This issue can be replicated without "creating stores from react" and without "store recreation" if you find `Store<Store<T>>` acceptable. If you're unhappy with that idea and this kind of meta usage is considered invalid, feel free to close the issue.

Example: https://share.effector.dev/7pXx6Vwr.

**Comment by zerobias** [comment]
Thanks, it became much clearer with new example 👍 

The reason why suggested solutions are not suited is that they bring new dynamic stores bugs too, just another ones. But I'm think I'm found a way to fix that without affecting anything else

**Comment by zerobias** [comment]
Fixed in `effector-react 21.3.2`

**Comment by nsf** [comment]
Thanks.
