### ISSUE TITLE
Specify target Vue versions (2 or 3) for different `effector-vue` APIs

### ISSUE THREAD

**Issue by onvlt** [effector/effector#491]
Correct me if I'm wrong, but it seems to me that different `effector-vue` APIs (especially Options API vs. Hooks API) assume different Vue versions.

For example, I tried to use Hooks API in combination with Vue 2 & `@vue/composition-api` but it won't compile because it tries to import composition functions directly from `vue` module (as in Vue 3) instead of `@vue/compositon-api` module (as in Vue 2). On the contrary, I suppose Options API won't work with Vue 3, because Vue 3 does not use global `Vue.use` plugin registration (but I'm not 100% sure, I did not try that).

Therefore I think that it would be very helpful if `effector-vue` documentation specified Vue versions explicitly in order to avoid confusion among library consumers. Maybe it could be broken into subsections by Vue versions – something like this:

- Vue 2
  -  VueEffector
  - ComponentOptions
- Vue 3
  - Gate API
  - Hooks API

**Comment by Fl0pZz** [comment]
https://github.com/vueuse/vue-demi

**Comment by ilajosmanov** [comment]
Hooks implemented only for Vue 3. 
Options API was implemented for both versions but we didn't release that because haven't types for Vue 3

**Comment by igorkamyshev** [comment]
As I understand, the latest version of Vue 2 (https://v2.vuejs.org/v2/guide/migration-vue-2-7) supports Composition API out of the box. So, shall we clouse this issue?
