### ISSUE TITLE
Unused variable in README docs in React example

### ISSUE THREAD

**Issue by loonywizard** [effector/effector#492]
Hi! It seems that there is unused variable `value` in "Increment/decrement with React" example from [README.md](https://github.com/effector/effector/blob/master/README.md#incrementdecrement-with-react)

```ts
const App = () => {
  // unused variable here
  const value = useStore(counter)

  return (
    <>
      <Counter />
      <button onClick={increment}>+</button>
      <button onClick={decrement}>-</button>
      <button onClick={resetCounter}>reset</button>
    </>
  )
}
```

If this variable declared here by purpose, maybe this line should be commented

**Comment by zerobias** [comment]
Examples in readme were very outdated; I found that it was better not to duplicate the documentation site, but to make a link to it larger
