### ISSUE TITLE
Typings of useEvent are incorrect

### ISSUE THREAD

**Issue by alatielle** [effector/effector#500]
## Missing/Incorrect APIs

The result of `someDomain.createEvent()` is assignable to `() => void`, but `useEvent(event)` is not:
```
TS2322: Type '(payload: void) => void' is not assignable to type '() => void'.
```

**Comment by zerobias** [comment]
Fixed in `effector-react 21.3.3`

**Comment by igorkamyshev** [comment]
I've found out that this issue exists in `useUnit`, so let me reopen it.

**Comment by sergeysova** [comment]
@igorkamyshev Can you reproduce this issue and create a new one with correct title?

(Because, I can't reproduce https://tsplay.dev/WyePbW)

**Comment by igorkamyshev** [comment]
Sure
