### ISSUE TITLE
Stale source value in guard, after setting it to undefined

### ISSUE THREAD

**Issue by montecamo** [effector/effector#502]
**What is the current behavior:**
`source` value not updates in `guard` after setting it to `undefined`

```
const increase = createEvent();
const clock = createStore(0).on(increase, (s) => s + 1);
setInterval(increase, 1000);

const updateSource = createEvent();
const source = createStore('source').on(updateSource, () => undefined);
setTimeout(() => updateSource(), 2000);

const target = createEvent();
target.watch(console.log);

guard({
  clock,
  filter: (s) => s !== undefined,
  source,
  target,
})
```

**Reproduce**: https://share.effector.dev/Ku6fzAVX

**What is the expected behavior:**: `target` should log nothing after `source` update

**Which versions of effector packages, and which browser and OS are affected by this issue? Did this work in previous versions of effector?:**
`effector@21.8.11`

**Comment by igorkamyshev** [comment]
Hello! It's expected behaviour. Store skips `undefined` as a value, you can read more about it here — https://effector.dev/docs/api/effector/store#ontrigger-reducer
