### ISSUE TITLE
Add alias for Event type, due to name collisions

### ISSUE THREAD

**Issue by PFight** [effector/effector#508]
Type with name Event is defined in lib.dom.d.ts and in react/global.d.ts. So, when I type Event VSCode does not suggest me make autoimport from effector, as it do for Store and other types.

Please, add alias for type, something like EffectorEvent.

**Comment by igorkamyshev** [comment]
I think, many libraries and frameworks use names like `Event`, `Store`, etc. So, in my opinion, it's absolutely okay. We have explicit imports in JS (TS), and this name collisions cannot break application.

If, we'll try to resolve these collisions, we should add `Effector` prefix to all types and functions, and it looks strange for me.

**Comment by PFight** [comment]
lib.dom.d.ts is the standard DOM typings, that included, I think, to all web projects. So, in every project autoimport of Event will not work. It means, that every effector developer should enter import { Event } from "effector" by hands every time it uses Event. You think it is ok?

**Comment by igorkamyshev** [comment]
Interesting case. Before my answer, I tried to write `Event`-type in my code and checked all VSCode suggestions.

<img width="597" alt="Screenshot 2021-08-11 at 14 19 38" src="https://user-images.githubusercontent.com/26767722/128986554-3b1ba77d-351a-4e5f-8bbb-94e9b4b3ca11.png">

As you can see, it suggests to import `Event` from `effector` package.

But, of course, I could be wrong.

**Comment by PFight** [comment]
Hm, looks like VSCode does not suggest import from effector until enter full type name:

![image](https://user-images.githubusercontent.com/198847/129075341-63132afa-4f7b-4316-aeb6-ed0ef03746f8.png)

![image](https://user-images.githubusercontent.com/198847/129075368-fd4222d5-f362-41b4-8d3d-54891134d548.png)

Thanks, it's plus minus normal.
