### ISSUE TITLE
Error in modal example

### ISSUE THREAD

**Issue by olegKusov** [effector/effector#513]
Error happens here -> https://share.effector.dev/B2ShiBzm

![image](https://user-images.githubusercontent.com/28058268/130262660-90d74e44-25bc-43eb-8b06-105960978665.png)

OS: Fedora 34
Firefox version: 90.02

**Comment by zerobias** [comment]
Looks like `new CSSStyleSheet()` is a [chrome-only feature](https://bugzilla.mozilla.org/show_bug.cgi?id=1595444), need to replace it with something more convenient

**Comment by egorguscha** [comment]
An [example](https://share.effector.dev/2rCS9bw1) was fixed, at the docs as well
