### ISSUE TITLE
Possible to watch() state rather than events?

### ISSUE THREAD

**Issue by slikk66** [effector/effector#514]
Hi we are using effector for our 2 newest projects and enjoying it! A new thing has come up where we have a few different createEvents that change a flag inside of the state. We would like to watch for when that flag changes.

Right now I have 2 different watch functions on the 2 createEvents, is it possible to just watch the state instead in some way?

Or is it simply to watch on all of the events and map a common function to all of them looking for the changed flag. 

Thanks!

**Comment by igorkamyshev** [comment]
Hello. Yes, it's possible

https://share.effector.dev/iQdbHu0a

You can call `watch` on any store.

**Comment by slikk66** [comment]
Thank you
