### ISSUE TITLE
Invalid editUrl for ru-version of doc

### ISSUE THREAD

**Issue by azinit** [effector/effector#515]
> I haven't found related issue, sorry if it is double

## Issue

There is incorrect url for editing article at russian version

### Expected result

`https://github.com/effector/effector/blob/master/website/client/i18n/ru/docusaurus-plugin-content-docs/current/introduction/installation.mdx`

### Actual result

`https://github.com/effector/effector/blob/master/docs/introduction/installation.mdx`

![image](https://user-images.githubusercontent.com/42924400/130478828-2039ff71-3d67-47f0-aeaf-18ee53c2b28b.png)

**Comment by azinit** [comment]
As I understand it, there is should be swtiched on flag `editLocalizedFiles: true`

https://docusaurus.io/docs/i18n/git#localize-edit-urls

![image](https://user-images.githubusercontent.com/42924400/130488336-1e6b71d8-81da-4155-b265-1dd0884619fc.png)

**Comment by egorguscha** [comment]
Fix https://github.com/effector/effector/commit/69f8ee12df8eb298863b135c5c3ab4bb8b34e98d
