### ISSUE TITLE
guard: expect clock to be a unit (store, event or effect) or array of units

### ISSUE THREAD

**Issue by smenshikov** [effector/effector#517]
**What is the current behavior:**
I can not build my project because of this error. 

**Please provide the steps to reproduce and if possible a minimal demo of the problem via https://share.effector.dev, https://codesandbox.io or similar**
I have this 
```
guard({
  source: startGetAfterpayTotal,
  filter: $isUSA,
  target: getAfterpayTotalFx,
});
```
So, `startGetAfterpayTotal` is event, `$isUSA` is store, `getAfterpayTotalFx` is effect. Nothing unusual, but in terminal I see this error `Error: guard: expect clock to be a unit (store, event or effect) or array of units`

**What is the expected behavior:**
Should work as the version 21.8.12

**Which versions of effector packages, and which browser and OS are affected by this issue? Did this work in previous versions of effector?:**
I use the latest version of effector 22.0.3. For version 21.8.12 works fine

Maybe any ideas what I can do to avoid this? 

Also, I have noticed - if I use `clock` intead of `source` in the `guard` construction then the error disappears. But is this behavior OK?

**Comment by smenshikov** [comment]
Forgot one thing - my app is based on Next.js. Looks like I just solved the issue. I removed the `.next` folder and again built the project. For now we can close this issue.

**Comment by zerobias** [comment]
Btw, I found an issue which leads to your error: if there are no source nor clock, then error will tell you about clock only, which is misleading
