### ISSUE TITLE
Merge guard and sample methods

### ISSUE THREAD

**Issue by val-o** [effector/effector#521]
## Proposal

Provide an ability to transform data from `clock` and `source` in `guard ` function. 

## Use case

Suppose we have a simple authentication flow, with following definitions

```ts


type UserName = string;
type Password = string;
type AuthFlowState = { type: 'WaitingUserName' } | WaitingPasswordState | { type: 'Done' };
type WaitingPasswordState = { type: 'WaitingPassword'; username: UserName };
declare const isWatingPassword: (state: AuthFlowState) => state is WaitingPasswordState;

const store$ = createStore<AuthFlowState>({ type: 'WaitingUserName' });

const submitPasswordEvent = createEvent<Password>();
type SubmitPasswordArgs = { password: Password; username: UserName };
const submitPassowrdFx = createEffect<SubmitPasswordArgs, unknown>();

guard({
  clock: submitPasswordEvent,
  source: store$,
  filter: isWatingPassword,
  target: submitPassowrdFx,
});

```

- The `submitPassowrdFx` should be called once `submitPasswordEvent` is fired, but only when `AuthFlowState` is in the right state
- Then we need to collect username from  `AuthFlowState`  and password from  `submitPasswordEvent`  params in order to call a `submitPassowrdFx` effect.

The code snipper above won't compile, due to types mismatch, because we also need to pass password from clock. If we would have a mapping function (like `fn` in `sample`), which would be called after filtering, we could easily shape a params expected by target effect

## Workaround

We can achieve desired behaviour by combining sample with guard as follows:

```ts

sample({
  clock: guard({ clock: submitPasswordEvent, source: store$, filter: isWatingPassword }),
  source: submitPasswordEvent,
  fn: (sourceParams, clockParams): SubmitPasswordArgs => ({
    password: sourceParams,
    username: clockParams.username,
  }),
  target: submitPassowrdFx,
});
```

**Comment by doasync** [comment]
![photo_2021-07-16_17-24-11](https://user-images.githubusercontent.com/29141708/132187478-1d78aebb-49ff-4e5c-9ca1-df4a7027d819.jpg)
https://share.effector.dev/xltBEcdq

**Comment by zerobias** [comment]
The reason why `fn` is still missing in `guard` is purely technical - it is quite difficult to write types for `guard`, so we have not yet succeeded in implementing this feature

**Comment by zerobias** [comment]
guard will be merged with the sample in the next minor release. right now I am working on [types for this feature](https://github.com/effector/effector/commit/c58c9aea71031e582f569aac2fe2fe8b2087203c)
