### ISSUE TITLE
The effect made with **attach** doesn't completely belong to the domain of the original effect

### ISSUE THREAD

**Issue by paladdins** [effector/effector#527]
**What is the current behavior:**
- The **attached** effect have the `parent` prop
- The **attached** effect's `compositeName.fullName` does not contain the full domain names' chain

As a result I can't properly use effector-logger with redux devtools :)

**Please provide the steps to reproduce and if possible a minimal demo of the problem via https://share.effector.dev, https://codesandbox.io or similar**
REPL https://share.effector.dev/FVbEUEmS

**What is the expected behavior:**
The **attached** effect's `compositeName.fullName` contains the full domain path to itself

**Which versions of effector packages, and which browser and OS are affected by this issue? Did this work in previous versions of effector?:**

- version ^21.8.12
- every browser

**Comment by sergeysova** [comment]
The attached effect correctly belongs to the domain. You can check it via `onCreateEffect` hook: https://share.effector.dev/FVbEUEmS

But another issues with defaultConfig parent and compositeName still here.

Thank you for the report
