### ISSUE TITLE
Impossible to pass typed event to sample's target

### ISSUE THREAD

**Issue by 7rulnik** [effector/effector#530]
## Missing/Incorrect APIs

It's impossible to pass typed `createEvent` to `sample`'s `target`. Take a look at `addNumberTyped`: 

```ts
import { sample, createStore, createEffect, createEvent } from 'effector';


const addNumber = createEvent()
const addNumberTyped = createEvent<number>()

const $userName = createStore('john')
const signIn = createEffect((params: any) => {
  console.log(params)
})
const submitForm = createEvent<number>()

sample({
  clock: submitForm /* 1 */,
  source: $userName /* 2 */,
  fn: (name, password) => ({name, password}) /* 3 */,
  target: [
    signIn /* 4 */,
    addNumber,
    addNumberTyped // will trigger error
})

submitForm(12345678)
```

**Playground Link:** [Provided](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgZwIbgDYFMA0cDGUWqMWAyjNLgUSVgKIBmjW+Mehxp9AblgHbwAvnEZQIIOAHIszVpShSA3AFgAUOvX4I-ZPFQATAwDkAriABGWKHAC8NLgz6CAFAEotOvXEMnzVqAAVAE8wLAM7BzpeARgAHn5-awA+d001bV14ABJTZGtjdCxIzjoKKhcpACsIAAt+KQ8Mr3hkYABzfgBJfhLabjk2FxcwVCh0ZAAuH35gtztkxHU4Ai8IbAA6DAh2kbGJpqEmzO9kUwsQYBgAMWhJe1LuZ3jEyxS0jTU0TCwXBGWCNt8ABraZnC5XW5QSQAegAVHAAIxwOEwnAA5AQUxQfBYaa5fJQQogYrwuAAJhRaIBjH40xc-CKeFGyGQAHdoAZ5rZFn9GSTmahWRyoAYjnAyQBmKnotQrGBjdpYGDTADaAJWbU6PQlCIALDKNT4jGY3lBZSsVr5TQEQmEDOojulwZcbncXIjyZK9QBWABsAHYABxNIA)

## Relevant documentation

* [createEvent](https://effector.dev/docs/api/effector/createEvent)
* [sample](https://effector.dev/docs/api/effector/sample#sampleclock-source-fn-target-greedy)

**Comment by YanLobat** [comment]
Hi, I guess this one is understandable since this is a type mismatch. If you return just password in `fn` TS won't cry. but you're trying to pass a shape to event which is just a number
