### ISSUE TITLE
Combine fails on large unions with object API but works via multiple arguments API

### ISSUE THREAD

**Issue by 7rulnik** [effector/effector#531]
## Missing/Incorrect APIs

The example below fails with `Type instantiation is excessively deep and possibly infinite.(2589)`.

It's obvious that this problem is related to `Currency` variations. It works with 14 elements, but not more. I also tried 4.5.0-beta with [Tail-Recursion Elimination](https://devblogs.microsoft.com/typescript/announcing-typescript-4-5-beta/#tailrec-conditional) but the result is the same.

Also, it could be workarounded via multiple arguments, but it leads to more verbose code.

```ts
import { createStore, combine } from 'effector';

type Currency = 'usd' | 'eur' | 'cny' | 'uah' | 'byn' | 'thb' | 'rub' | 'azn' | 'kzt' | 'kgs' | 'uzs' | 'tzs' | 'kes' | 'zar' | 'ron' | 'mdl' | 'ils' | 'inr' | 'pln' | 'chf' | 'gbp';


const initialValue = 'usd' as Currency;

const $currency = createStore<Currency>(initialValue)

type AutosearchTrigger = {
  currency: Currency;
};

// Will fail with «Type instantiation is excessively deep and possibly infinite.»
const $autosearchTrigger = combine<AutosearchTrigger>({
  currency: $currency,
});


const $autosearchTriggerViaTuple = combine<Currency, AutosearchTrigger>($currency, (currency) => ({
  currency
}));
```

**Playground Link:** [Provided](https://www.typescriptlang.org/play?ts=4.4.3#code/JYWwDg9gTgLgBAbzgYygUwIYzQZRtNAGhQhACNgA7NOAXzgDMpS4ByNBhtZfKVgbgCwAKBEwAnmBoBhAK5R0lZOLgBeNrIDOAE1ZwAPmzTy9h1skrjTGjAAtrrMuMoOYtsg6iyPBthgBeLr6sANb+MA4hAOaaDrL+scEwCZFoiWb+GHzBzEFmINoANg7AhelsVNlmYIV5bMi2DA5RZGACIh3CyBCUmvBUwDDAGIUAaiOyNOqsWrpwGJpwcgpoSuJCol09fXAAJMjyispqKOhYuLxoADzLR+IAfAAUA0Mj44WTAJSdElJwAIKyfCaTBQBoAFSgwCiUTQUBOCBEcBQh1WygAXEtUWsNrQNiIAPQEuAAdVKhUYGFKcAA7oNbHAANXgyQ0Kh9DCUV5DHpwYCLNAAD2QaU0wAAbmhCiptGg0GB5pRtHBIJoxWRpXzKAwXmgAHQAbpE3V68F2GCBEBBWQhUJhcJO3XIVGugOBoNt0NhUCeiOEyIOKzWmP22OUhBEtE++M2Jp25st1rBtkhXrho2G4NkNSmJGd1BuYfExDdVo9Kbt3qeoaD4bgj0Dd0+anu9b9AaLkc+0aAA)

## Relevant documentation

[combine(...stores, fn)](https://effector.dev/docs/api/effector/combine#combinestores-fn
) works
[combine({ A, B, C }, fn?)](https://effector.dev/docs/api/effector/combine#combine-a-b-c--fn) doesn't work

**Comment by sergeysova** [comment]
It is better not to pass generic arguments to combine.
Try to remove them and left all work to typescript.

**Comment by zerobias** [comment]
Fix will be published in the next minor release but looks like typescript 4.5.0 already added support for that case on their side

**Comment by 7rulnik** [comment]
@zerobias I can still reproduce it with 4.5.2
https://www.typescriptlang.org/play?ts=4.5.2#code/JYWwDg9gTgLgBAbzgYygUwIYzQZRtNAGhQhACNgA7NOAXzgDMpS4ByNBhtZfKVgbgCwAKBEwAnmBoBhAK5R0lZOLgBeNrIDOAE1ZwAPmzTy9h1skrjTGjAAtrrMuMoOYtsg6iyPBthgBeLr6sANb+MA4hAOaaDrL+scEwCZFoiWb+GHzBzEFmINoANg7AhelsVNlmYIV5bMi2DA5RZGACIh3CyBCUmvBUwDDAGIUAaiOyNOqsWrpwGJpwcgpoSuJCol09fXAAJMjyispqKOhYuLxoADzLR+IAfAAUA0Mj44WTAJSdElJwAIKyfCaTBQBoAFSgwCiUTQUBOCBEcBQh1WygAXEtUWsNrQNiIAPQEuAAdVKhUYGFKcAA7oNbHAANXgyQ0Kh9DCUV5DHpwYCLNAAD2QaU0wAAbmhCiptGg0GB5pRtHBIJoxWRpXzKAwXmgAHQAbpE3V68F2GCBEBBWQhUJhcJO3XIVGugOBoNt0NhUCeiOEyIOKzWmP22OUhBEtE++M2Jp25st1rBtkhXrho2G4NkNSmJGd1BuYfExDdVo9Kbt3qeoaD4bgj0Dd0+anu9b9AaLkc+0aAA

Thanks, will wait for release
