### ISSUE TITLE
Forbid imperative calls of effector units from reducers

### ISSUE THREAD

**Issue by AlexandrHoroshih** [effector/effector#541]
## Proposal

Throw error or show a console warning, if event or effect have been manually called from inside of store reducer or other pure functions.

Currently `effector` does not forbid or warn about event or effect calls inside reducers or other supposed-to-be-pure functions like `fn` of sample or `combine` rule

But, as it can be seen [at effector telegram chat](https://t.me/effector_ru/226612), many people do call events from reducers sometimes (and sometimes for a really long time) and have no clue, that it is not how it supposed to work.

Even though effector, apparently, still can handle that, using events this way goes way too much aganist declared rules and some projects may found themselves absolutely incompatible with some future release of effector

I think, explicit warning (or even exception) like
```
effector events must not be called from pure functions like store reducers or fn of sample.
Use effector operators instead.
Or, if you really need imperative control flow, use watch or effect for that
```
will help a lot here

## Use case

Today an effector user shared the way he has been using `.on` for a long time - it was something like this:
```ts
// this code must be either rewritten to operators or written in the same way, but inside `.watch`
$store.on(someEvent, (state, payload) => { 
 // store reducer meant to update stored value
 if (payload.some) {
   // but there is some control flow happening instead, which is wrong
   someEffect(state)
 } else {
  someOtherEvent(payload)
 }
 // next state is never returned - plain wrong usage of `.on`
})
```
From his words, he was using effector like that from the very beginning and have not seen any problems yet.

**Obviously**, all of it mentioned in the documentation, but it looks like that sometimes people do not read it carefully enough and little push is needed

**Comment by sergeysova** [comment]
@zerobias What about to add some extra parameter to a [`compute`](https://github.com/effector/effector/blob/b1c2b52b99f24b3f1b82ed726f86b294d81bde4a/src/effector/step.ts#L100)

And in the [appropriate switch/case](https://github.com/effector/effector/blob/b1c2b52b99f24b3f1b82ed726f86b294d81bde4a/src/effector/kernel.ts#L383-L403) check it only if parameter is `true`?

it could shoot me in the foot?

**Comment by zerobias** [comment]
@sergeysova well, looks like it should work in that way, let's try 👌

**Comment by zerobias** [comment]
Deprecation warning will be published in the next minor release

**Comment by RemoteRacoon** [comment]
> ## Proposal
> Throw error or show a console warning, if event or effect have been manually called from inside of store reducer or other pure functions.
> 
> Currently `effector` does not forbid or warn about event or effect calls inside reducers or other supposed-to-be-pure functions like `fn` of sample or `combine` rule
> 
> But, as it can be seen [at effector telegram chat](https://t.me/effector_ru/226612), many people do call events from reducers sometimes (and sometimes for a really long time) and have no clue, that it is not how it supposed to work.
> 
> Even though effector, apparently, still can handle that, using events this way goes way too much aganist declared rules and some projects may found themselves absolutely incompatible with some future release of effector
> 
> I think, explicit warning (or even exception) like
> 
> ```
> effector events must not be called from pure functions like store reducers or fn of sample.
> Use effector operators instead.
> Or, if you really need imperative control flow, use watch or effect for that
> ```
> 
> will help a lot here
> 
> ## Use case
> Today an effector user shared the way he has been using `.on` for a long time - it was something like this:
> 
> ```ts
> // this code must be either rewritten to operators or written in the same way, but inside `.watch`
> $store.on(someEvent, (state, payload) => { 
>  // store reducer meant to update stored value
>  if (payload.some) {
>    // but there is some control flow happening instead, which is wrong
>    someEffect(state)
>  } else {
>   someOtherEvent(payload)
>  }
>  // next state is never returned - plain wrong usage of `.on`
> })
> ```
> 
> From his words, he was using effector like that from the very beginning and have not seen any problems yet.
> 
> **Obviously**, all of it mentioned in the documentation, but it looks like that sometimes people do not read it carefully enough and little push is needed

But what if I want to create an effect which triggers 2 effects which are expected to be done together?
```
const effect = createEffect(() => Promise.all([fx1, fx2]))
```
If we write this way we get the warning in console as well

**Comment by zerobias** [comment]
There should be no warning in your case, it’s valid usage
