### ISSUE TITLE
Method `when`

### ISSUE THREAD

**Issue by sergeysova** [effector/effector#555]
Sometimes you need to enable logic only when condition is met.

## Proposal

Is to add new method `when` enables logic inside callback to work only when condition is met:

```ts
import { when, createStore, combine, createEvent, sample } from 'effector';

export const $authorized = createStore(false);

const pageMounted = createEvent();
const $counter = createStore(0);

when($authorized, () => {
  $counter.on(pageMounted, (counter) => counter + 1);
  // or
  sample({
    source: $counter,
    clock: pageMounted,
    fn: counter => counter + 1,
    target: $counter,
  })
})
```

## Use case

Without this method each operator should be wrapped with `guard`

```ts
import { when, createStore, combine, createEvent, sample, guard } from 'effector';

export const $authorized = createStore(false);

const pageMounted = createEvent();
const $counter = createStore(0);

// Cannot be used, cause it works always
// $counter.on(pageMounted, (counter) => counter + 1);

sample({
  source: $counter,
  clock: guard(pageMounted, { filter: $authorized }),
  fn: counter => counter + 1,
  target: $counter,
})
```

**Comment by igorkamyshev** [comment]
Does this API require creating and deleting unit connections dynamically?

**Comment by sergeysova** [comment]
@igorkamyshev No, it should works like guard.

**Comment by doasync** [comment]
I suggest just adding `fn` to the `guard`

Then it would be possible to replace such a `sample`:
```ts
sample({
  source: $counter,
  clock: guard(pageMounted, { filter: $authorized }),
  fn: counter => counter + 1,
  target: $counter,
})
```
with `guard`
```ts
guard({
  filter: $authorized,
  source: $counter,
  clock: pageMounted,
  fn: counter => counter + 1,
  target: $counter,
})
```

This will increase readability compared to sample + guard, because `guard` immediately tells us that there is some kind of conditional logic going on

**Comment by sergeysova** [comment]
But if you need to wrap several operators to single guard, you have to duplicate guards

**Comment by doasync** [comment]
Yes, you would need to write multiple guards, but that's not duplication, that's using the operator for its intended purpose. Filters will be specified explicitly, you won't need to keep in mind that you are inside a condition, you can also add/remove conditions on the spot. 

Using operators inside callbacks is unusual for code on an effector, normally the logic is described at the top level. 

There is also a danger that users will start abusing nesting.

**Comment by sergeysova** [comment]
I don't see abusing in `when` method. It is using the operator for its intended purpose.
I like simplicity, and I don't like to repeat `guard` over and over for each operator in my system.

**Comment by sergeysova** [comment]
@zerobias I think it can work like withRegion.

```js
// pseudocode

let whenRef = null

function sample({ clock, ...otherOptions }) {
  let localClock = clock
  if (whenRef) {
    localClock = guard({ filter: guardRef, clock })
  }
  
  // Do other work
}

function guard({ source, clock, filter }) {
  let localFilter = filter
  if (whenRef) {
    localFilter = combine(filter, whenRef, (f, r) => f && r)
  }

  // Do other work
}

function when(condition, fn) {
  const prevRef = whenRef
  whenRef = condition
  fn();
  whenRef = prevRef
}
```

**Comment by zerobias** [comment]
instead of adding yet another method, I would prefer to extend `split` in this way

```jsx
import { split, createStore, combine, createEvent, sample } from 'effector'

export const $authStatus = createStore<'user' | 'guest'>('guest');

const pageMounted = createEvent();
const $counter = createStore(0);

split({
  match: $authStatus,
  cases: {
    user() {
      $counter.on(pageMounted, (counter) => counter + 1);
      // or
      sample({
        source: $counter,
        clock: pageMounted,
        fn: counter => counter + 1,
        target: $counter,
      })
    }
  }
})
```

**Comment by Kelin2025** [comment]
Idea with `split` looks interesting, it's like `variant` in `forest`

Speaking of examples - I have a complex editor and I want to split it onto separate features. For example, I have options modal window with a form. Simplified form:
```tsx
const optionsModalOpened = createEvent<Options>()
const optionsSaved = createEvent()
const optionsClosed = createEvent()
const $options = createStore(...)
```
When `optionsModalOpened` is triggered, passed options are stored to local `$options` store
When `optionsSaved` is triggered, `$options` move to the original options
I'd like to separate it, but also it'd be good to make it re-usable in other places. So we can call `optionsModalOpened` from different parts of the application and `optionsSaved` would save to the place from where we opened the modal
Currently it's kinda verbose:
```tsx
const $isOpened = createStore(false)
const $blocks = createStore([{ title: "Block", options: { foo: "bar" } }])
const $currentIdx = createStore(-1)

const blockOptionsModalOpened = createEvent<{ idx: number, options: Options }>()

$isOpened
  .on(blockOptionsModalOpened, () => true)
  .reset(optionsSaved)
  .reset(optionsClosed)

$currentIdx
  .on(blockOptionsModalOpened, (prev, { idx }) => idx)

$blocks.on(
  // And here we have to use guard
  guard({
    source: [$currentIdx, $options],
    clock: optionsSaved,
    filter: $isOpened,
  }),
  (blocks, [currentIdx, options]) => ...
)
```
If there's only one event, that's probably fine. But on the current project I have a window that opens to the side and updates data in realtime + it has a bunch of buttons that aren't directly related to options. Which means I should map all the events and wrap them into guard

**Comment by Kelin2025** [comment]
Filtering stuff only for authorized users is also a great example, 'cause you often want to completely block some feature unless it's allowed. In this case, it would be good to have an opportunity to do "else" statements - here `split` variant is better than `when`

Speaking of `split` - there's one important difference between `spit` and `when`. `split` semantically tells you to group stuff under a single `split` statement. What I mean is that my example with options modal implicitly tells you to write these conditions inside the modal feature itself

```tsx
split({
  match: $openedBy,
  cases: {
    editor () { save there },
    botsList () { save here },
    ...
  }
})
```

`when`, on the other hand, looks more like a local casual approach, which can be used just to wrap existing code into a single `if (bool) {}`

So, I think that both variants have pros and cons

**Comment by Kelin2025** [comment]
By the way, since we have `variant` in `forest`, we also have `route` for single simple statements. So, I guess, we should do the same here

**Comment by Kelin2025** [comment]
Another advantage of `when` method - you can write utility wrappers without thinking about `filter` method  
For example, I have an utility for hotkeys:
```tsx
hotkey("Ctrl+Z", undo)
hotkey("Ctrl+Shift+Z", redo)
```
I won't deep-dive into `hotkey` mechanics, let's say this method just takes global `keypress` event and filters it by using `guard`:
```tsx
const hotkey = (key, event) => {
  return guard({
    clock: keypress,
    filter: e => /* check key combination */,
    target: event
  })
})
```
If I want to implement custom filtering (e.g. enable hotkey only when specific page is opened or whatever), I need to implement `filter` option for this method:
```tsx
hotkey({
  bind: "Ctrl+Z",
  filter: $isEditorOpened,
  target: undo
})

hotkey({
  bind: "Ctrl+Shift+Z",
  filter: $isEditorOpened,
  target: redo
})
```
Or wrap `undo` into guard
```tsx
hotkey("Ctrl+Z", guard({ target: undo, filter: $isEditorOpened }))
hotkey("Ctrl+Shift+Z", guard({ target: redo, filter: $isEditorOpened }))
```

But instead, I could just rely on `when` function which will automatically wrap all inner connections
```tsx
when($isEditorOpened, () => {
  hotkey("Ctrl+Z", undo)
  hotkey("Ctrl+Shift+Z", redo)
})
```

**Comment by zerobias** [comment]
Curiously, your last case can be solved with another your proposal:

```js

guard({
  clock: keypress,
  filter: [
    $isEditorOpened,
    e => /* check key combination */
  ],
  target: event
})

```

**Comment by zerobias** [comment]
The issue with `when` is that it is strictly exclusive and your example show glimpses of patter matching behavior, not an evidence of single all-in flag for vast blocks of code
What are you going to do when your cases finally stop to intersect?
Try to draw interactive illustration for `sample`:

Should I draw a row with a word `target`? Yes, in some of the cases, easy branching
Should I draw arguments for `fn` and how?
- when there is a `source` field and no `clock` field then draw `(src) => {}`
- when there is a `clock` field and no `source` field then draw `(clk) => {}`
- when there is a `source` field and a `clock` field then draw `(src, clk) => {}`
- there may be no fn at all!

With `when` you’ll have to write a lot of nested callbacks and you’ll easily miss a lot of cases.
So no, they are not nested, they are flat, which imply that this helper will be strongly limited solution for a narrow edge case like object form of `restore` or any other near-obsolete methods for the problems which are not exist anymore


tl tr: if your method imagined in a config form become too verbose or useless then it solves nothing

**Comment by zerobias** [comment]
in other words, __don’t even try to suggest methods without config form__, they will be rejected for sure. shorthands shall appear as updates of existing features after _long_ production history. `useStoreMap` has a nice shorthand `useStoreMap(store, fn)` only because it was released in a config form, therefore method `when` will not be released as a shorthand for nothing

**Comment by zerobias** [comment]
What makes me sad is that after a two weeks of discussion nobody yet realizes that in object form that suggestion becomes a mirror of a guard
```js
when({
  filter: $isEditorOpened,
  target() {
    whatever
  }
})

guard({
  filter: $isEditorOpened,
  target() {
    whatever
  }
})
```

Which render the new method basically unnecessary

Deploy another pile of methods to particular problems is always such an easy-peasy way to solve them. That a cognitive bias which lead to code rot.

> Leidy Klotz, an engineer at the University of Virginia, noticed that minimalist designs, in which elements are removed from an existing model, were uncommon. So he reached out to Gabrielle Adams, a social psychologist at the university, to try to figure out why this was the case. The two researchers hypothesized that there might be a psychological explanation: when faced with a problem, _people tend to select solutions that involve adding new elements rather than taking existing components away_

[Additive cognitive bias](https://smarter.blog/additive-cognitive-bias/)

I’m not against the idea itself, just read an article above, modify proposal to fit into an existing api and open a new issue

**Comment by zerobias** [comment]
Please, _working_ examples first. If you don’t deep-dive into details then I cannot suggest any alternative solution
@Kelin2025 @sergeysova 

My point is that the difference will be seen as the project grows, and even if you can describe the project in words, you can't describe "the growth", we can only take a real code and see

**Comment by sergeysova** [comment]
@zerobias What about to add API you shown:

```ts
guard({
  filter: $isEditorOpened,
  target() {
    hotkey("Ctrl+Z", undo)
    hotkey("Ctrl+Shift+Z", redo)
  }
})
```

Looks great!

**Comment by zerobias** [comment]
guard itself is going to be merged to sample, so this eventually becomes
```js
sample({
  filter: $isEditorOpened,
  target() {
    hotkey("Ctrl+Z", undo)
    hotkey("Ctrl+Shift+Z", redo)
  }
})
```
Looks futuristic but I need to

**Comment by zerobias** [comment]
Damn)

**Comment by sergeysova** [comment]
I'am closing this issue, because it is not about method `when` it is about another feature of the `sample`
