### ISSUE TITLE
Error in Gate Recipe

### ISSUE THREAD

**Issue by PetrovaDaria** [effector/effector#560]
When trying out the code of the gate recipe (https://effector.dev/docs/recipes/react/gate), there is an error in console 
```
TypeError
Cannot convert undefined or null to object
Todo
repl.js:33:4
```
It can be fixed if we write on line 32 `if (!todo || Object.keys(todo).length === 0)` instead of `if (Object.keys(todo).length === 0)`

**Comment by egorguscha** [comment]
fixed in de3b0da1ef5ff90393af7a6be5a214de77f8133b
