### ISSUE TITLE
Deprecate derived units in `target`

### ISSUE THREAD

**Issue by AlexandrHoroshih** [effector/effector#563]
**What is the current behavior:**
Usage of `.on` method is deprecated on derived stores and to be removed in the next release - this is very good news and, i think, makes everything a lot more consistent and predictable 👍 

But now usage of derived stores as a `target` in operators is not warned or error by effector, so the problem of unexpected changes to derived stores still persists 😢 

```ts
$readOnlyStore = $store.map(v => v)

// yay! error in console!
$readOnlyStore.on(ev, () => {})

// no error :(
sample({
 clock: $store,
 target: $readOnlyStore,
})
```
Also i think that stores created by restore from an event or effect should be considered as derived too, since they also have explicit dependency at the moment of creation: restore(changed, null) 🤔
UPD: Since restored event state still can be used by app and can't be derived from, for e.g., state in serialized scope during SSR, it is definetly not derived (at least, in a sense similiar to mapped stores)

**Please provide the steps to reproduce and if possible a minimal demo of the problem via https://share.effector.dev, https://codesandbox.io or similar**

https://share.effector.dev/yqvd359F

**What is the expected behavior:**
Any attempt of adding a new source of updates to dervied store is forbidden and warning/error is shown.
If such behaviour is needed - it is better to create classic (not derived) store and subscribe it to changes of original derived store.

**Which versions of effector packages, and which browser and OS are affected by this issue? Did this work in previous versions of effector?:**
`effector@22.0.0^`

**Comment by zerobias** [comment]
So we need to add such validations to:
- forward to
- sample target
- guard target
- split cases

Anything else?

**Comment by sergeysova** [comment]
Maybe add validation on the kernel level? To add support for patronum

**Comment by zerobias** [comment]
This is added to the metadata of the graph node anyway, assume something like that:

```js
if (unit.graphite.meta.derived) throw Error('derived unit cannot be used as a target')
```

**Comment by AlexandrHoroshih** [comment]
I updated a REPL example a bit:
- dervied events in `target` are also not warned yet
- `merge` returns an not-derived unit and its direct call is not warned

https://share.effector.dev/0f1bnC6c

**Comment by zerobias** [comment]
@AlexandrHoroshih thanks, I wrote more tests based on your findings

**Comment by sergeysova** [comment]
> Also i think that stores created by restore from an event or effect should be considered as derived too, since they also have explicit dependency at the moment of creation: restore(changed, null) 🤔

I cannot agree. `restore(event, default)` invented to be a shortcut for `createStore(default).on(event, (_,i) => i)`. So it is should create a NEW store. Example use case:

```ts
const nameChanged = createEvent<string>();
const $name = restore(nameChanged, '');
```

But in real life you want to reset form and load data to form fields:

```ts
$name.reset(formCleanup);

spread({
  source: formLoadFx.doneData,
  targets: {
    name: $name,
  },
})
```

As we see it is a common store, not derived.

**Comment by AlexandrHoroshih** [comment]
> I cannot agree. restore(event, default) invented to be a shortcut for createStore(default).on(event, (_,i) => i). So it is should create a NEW store

It is how it works know, yes, but same works for mapped stores know

But yeah, restored event is probably not a derived store, because its state definitely should be transferred over the network during SSR - otherwise app rendered on the client will be different from the render at server

**Comment by sergeysova** [comment]
> but same works for mapped stores now

Not the same semantics.

Mapped store it the explicit contract with the single source of truth (single source of updates).

Here we proof store has no updates source except `$a`:
```ts
$b = $a.map(fn)
```

Here the same, but source of updates is `$c` AND `$d`:

```ts
$e = combine($c, $d, (c, d) => c + d)
```

**Comment by zerobias** [comment]
Deprecation warning will be published in the next minor release
