### ISSUE TITLE
Do not trigger for defaultState

### ISSUE THREAD

**Issue by KenjiTakahashi** [effector/effector#570]
I am modelling stores that are backed by data retrieved from the backend API.
In this case, the value provided as `defaultState` to `createStore` often doesn't make sense to the app. I'd like to avoid retrieving it in the `watch` callbacks to not trigger unnecessary operations (which might also break stuff sometimes, although that's likely just how existing parts of the app are structured).

Basically something like this https://share.effector.dev/hVE6Xfsp, except that I don't want that initial `undefined` (or whatever) to appear.

Of course I could ignore it in the `watch` itself, but that's not very feasible.

Is this possible to achieve somehow? Thanks!

**Comment by zarabotaet** [comment]
What do you use `watch` for?
As the logic of the project becomes more complex, it is better to replace it with a combination of `effect` and `sample`. 
like this https://share.effector.dev/0QmqTWrR
Such combination provides skipping initial trigger of effect out of the box.

**Comment by AlexandrHoroshih** [comment]
Simpler solution for your case would be to just watch to `$store.updates` event instead of `$store` itself - it will behave exactly like you want

But yeah, it is much better to avoid logic inside `.watch` and prefer effector's [effects](https://effector.dev/docs/api/effector/effect) for side-effects and operators like [`sample`](https://effector.dev/docs/api/effector/sample) or [`guard`](https://effector.dev/docs/api/effector/guard) instead - it will give you a lot more control over which logic or effects should be executed and when

Watchers are more useful for integrations with other libs, like `react` or for building custom operators, like ones in `effector/patronum`

**Comment by KenjiTakahashi** [comment]
I am using `watch` to update component state and render the view.
I agree that using `guard` would probably be the cleanest way here. Except that it would give me back an `Event` or `Effect`, which I cannot further `combine`. And if I target another `Store`, I'm back to square one.

The bigger idea I have is to have 2 "levels" of stores:
Lower level that exposes the smallest units possible, but still usable on their own.
Higher level that allows combining the stores retrieved from the lower one.

So if I wanted to `guard` the lower level store, it would not be usable in the higher one(s) anymore.
I can provide some helper wrapper that does this optionally, but that again moves the burden to the caller.

I have totally overlooked `$store.updates`, though. This might be what I need indeed.

**Comment by AlexandrHoroshih** [comment]
If you using `react` or `vue` for UI, then there are [`effector-react`](https://effector.dev/docs/introduction/installation#for-react) and [`effector-vue`](https://effector.dev/docs/introduction/installation#for-vue) packages, so you don't have to bother yourself with your own bindings

Or you using something else? @KenjiTakahashi

**Comment by KenjiTakahashi** [comment]
Yes, I'm aware of these. Unfortunately, this is quite old code using a mixture of AngularJS and custom stuff. Moving to framework independent store management is actually part of the process to eventually swap this out.

For now I got it working with the `$store.updates`, it should be good enough I think. Thanks guys!
