### ISSUE TITLE
change restore api

### ISSUE THREAD

**Issue by olegKusov** [effector/effector#583]
## Proposal

Now with restore we can make 3 different things:
1. create store from event.
2. create store from success fx
3. create an object with stores from object with values

It makes restore api inconsistent and we need everytime use createEvent. It's annoying. My RFC. 

1. for events: `const [$store, setStore] = restore(null);`
2. for effects: `const $store = restore(null, fx.done);`
3. for creating an object with stores: `const {foo: $foo, bar: $bar} = divide({
  foo: 'foo',
  bar: 0,
})`

I need every time manually create events for restore. It's waste of time. In my cases I use restore for event creating most of time that's why for me it's has maximum priority.

**Comment by zerobias** [comment]
`setStore` is an anti-pattern, you need to describe _what happened_ in an application, not which consequences you aimed for. 
## Examples
### **I want to do X:**
```js
const setFormValues = createEvent()
const $formValues = restore(setFormValues, {email: '', age: 18})
```
`setFormValues` focused on implementation details that can and _will_ change thereby forcing you to change `setFormValues` too


### **Here what happened in application:**
```js
const formSubmitted = createEvent()
const $formValues = createStore({email: '', age: 18})
  .on(formSubmitted, (_, update) => update)
```

`formSubmitted` describe a step in a user registration workflow of [business logic](https://en.m.wikipedia.org/wiki/Business_logic). This is an _essential_ part of definition of that business workflow and it will exist while **project owners interested in that feature**. And the fact that triggering of this event will change the store is just an implementation detail and could be freely changed during refactoring without affecting UI at all. To protect UI and business events from irrelevant changes, they shouldn’t know what happened when they trigger something.

The difference is that when you try to apply a second approach, you would found that stores are actually changed by different scenarios and your old `change*` events appeared across different business scenarios what make application more entangled and brittle than it would be 


I advise you to read the first chapter of [Reactive Design Patterns](https://www.manning.com/books/reactive-design-patterns), it will explain that idea further
