### ISSUE TITLE
Add `classList` to `spec()` to allow independently changing CSS-classes

### ISSUE THREAD

**Issue by sergeysova** [effector/effector#599]
## Problem

Sometimes I need to set CSS-classes for single element from different places. For example:

```ts
function Card(fn) {
  h('div', {
    attr: { class: 'padding-4' },
    fn() {
      fn()
    },
  })
}

Card(() => {
  spec({ attr: { class: 'bg-white' } })
})
```

But the second class attr in the spec won't work.

## Proposal

I propose to add support for [`classList`](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList).

1. Object form of classes, allows to enable/disable class via boolean-store value

```ts
spec({
  classList: { 'size-big': $isBig, white: true }
})
```

2. Array form must allow to enable classes provided by store:

```ts
const $size = createStore('size-big');

spec({
  classList: [$size, 'enabled']
})
```

3. Different calls of spec with `classList` should merge (lower one wins?)

```ts
h('div', () => {
  spec({ attr: { class: 'zero' } })
  spec({ classList: { first: true, second: false } })
  spec({ classList: ['second', 'third'] })
})
```

should be rendered as

```html
<div class="zero first second third"></div>
```

**Comment by zerobias** [comment]
The combination of objects for conditionals and arrays for strings/string stores is really amazing, it's solve all the issues around usage of that api

**Comment by sergeysova** [comment]
Released in https://github.com/effector/effector/releases/tag/forest%400.21.0
