### ISSUE TITLE
Multiple passes of `effector/babel-plugin` results in broken code

### ISSUE THREAD

**Issue by AlexandrHoroshih** [effector/effector#601]
**What is the current behavior:**
`effector/babel-plugin` is required for both SSR and testing + it is also useful for devtools like `effector-logger` - which uses it under the hood in its `effector-logger/babel-plugin` - which can lead to multiple passes of `effector/babel-plugin` on the code.

But currently mulitple passes of effector's babel-plugin are breaking the code of the app with errors like `combine expects a store in a field clock` - which is not the case in the user code

Looks like `effector/babel-plugin` does not check if some operator was already handled by it:
```ts
// after first plugin run
sample({
  and: [{
    source: $myCoolStore,
    clock: myEvent,
    target: myTarget
  }],
  or: {
    sid: "-tig1vb"
  }
});

// after second run
sample({
  and: [{
   // previous params are copied in a straightforward way - invalid config for sample as a result
    and: [{
      source: $myCoolStore,
      clock: myEvent,
      target: myTarget
    }],
    or: {
      sid: "-tig1vb"
    }
  }],
  or: {
    sid: "-tig1vb"
  }
})
```

**Please provide the steps to reproduce and if possible a minimal demo of the problem via https://share.effector.dev, https://codesandbox.io or similar**

Run `npm run bug` in console:
https://stackblitz.com/edit/node-ncjf3q?file=babel.config.js
Example of broken code can be found at `dist/index.js` after build

Same, but for effector@21
https://stackblitz.com/edit/node-zkwl3s?file=dist/index.js

**What is the expected behavior:**
I think that multi-pass of `babel-plugin` must be either correctly supported in some determenistic way (e.g. each pass adds or overrides metadata from previous runs in `or` field) or completely banned with explicit error

**Which versions of effector packages, and which browser and OS are affected by this issue? Did this work in previous versions of effector?:**
Probably all versions with babel-plugin

**Comment by zerobias** [comment]
Need to reproduce exact case: this is an issue with sample, combine or both?

**Comment by AlexandrHoroshih** [comment]
Updated reproduce:
https://stackblitz.com/edit/node-ncjf3q?file=index.js
Combine's value becomes corrupted, `attach`, `sample` and `forward` are throwing error about invalid config

**Comment by zerobias** [comment]
The fix will be published in next minor release
