### ISSUE TITLE
Function name conflict, unexpected parameter mutation - effector/babel-plugin

### ISSUE THREAD

**Issue by 7iomka** [effector/effector#603]
Somewhere inside your code (in my case, is a custom react hook, for example [usePress from yandex](https://github.com/bem/web-platform/blob/7a851a74e4ba61a2b288a3fc3485cfd73ae1bfd6/src/interactions/press/usePress.ts#L116) )
```ts
const attach = (target: T, id: number) => {
      cache.currentPointerTarget = target;
      cache.currentPointerId = id;
      cache.isPressed = true;

      disableTextSelection();
      setPressed(true);
};
// ..
attach(event.currentTarget, event.pointerId);
```

**What is the current behavior:**
`effector/babel-plugin` mutate at least first parameter `target` when function with the same name as api method get called
So, `target` in this example instead of and DOM element is transformed into
```ts
{
  and: DOM ELEMENT HERE,
  or: {sid: xxx}
}
``` 
**What is the expected behavior:**
The source code of the corresponded file does not change if the function that is used
- is defined in the same file
- imported from anywhere exc. effector, even if the name of this function is the same as the name of one of the effector API methods.

**Which versions of effector packages, and which browser and OS are affected by this issue? Did this work in previous versions of effector?:**
Latest Effector version.

The only workaround for now is to manually rename all source files that contains the same function names as effector API (not sure if all, but at least `attach`)

**Comment by zerobias** [comment]
**babel.config.js**
```js
module.exports = () => ({
  plugins: [],
  overrides: [
    {
      test: (filename) => !filename.includes('usePress'),
      plugins: ['effector/babel-plugin']
    }
  ]
})
```

I wonder why that babel feature is such well-hidden, I thought that using it is a no-brainer but it turns out to be an obscure voodoo :/

**Comment by zerobias** [comment]
Would you like to tell please, which one is your case exactly: function called in a same file or imported from somewhere?

**Comment by 7iomka** [comment]
> Would you like to tell please, which one is your case exactly: function called in a same file or imported from somewhere?

At the moment, as you can see from example above, unexbected behavior is actual when you called function in the same file, but some tests needed also for cases when I export this function declaration and use it in another file.

**Comment by zerobias** [comment]
Thanks for the report! It was an insidious bug that has been eluding us for a long time. The fix will be published in next minor release
