### ISSUE TITLE
Replacement of `values` during `fork` brakes serialization ignore

### ISSUE THREAD

**Issue by igorkamyshev** [effector/effector#609]
**What is the current behavior:**

1. Create non-serializable store (with `serialize: 'ignore'`)
2. Change its value during `fork`
3. Serialize fork values
4. Value of store will be serialized

**Please provide the steps to reproduce and if possible a minimal demo of the problem via https://share.effector.dev, https://codesandbox.io or similar**

https://share.effector.dev/CNYd8jSq

**What is the expected behavior:**

1. Create non-serializable store (with `serialize: 'ignore'`)
2. Change its value during `fork`
3. Serialize fork values
4. Value of store **won't** be serialized

**Which versions of effector packages, and which browser and OS are affected by this issue? Did this work in previous versions of effector?:**

`master`

**Comment by sergeysova** [comment]
Dear newcomers, research can be started from this place https://github.com/effector/effector/blob/master/src/effector/fork/fork.ts

**Comment by kireevmp** [comment]
@igorkamyshev this looks fixed by #903. Can you check if the issue is still relevant?

**Comment by igorkamyshev** [comment]
Yep, it's fixed
