### ISSUE TITLE
Deprecate `scope`-less runtime

### ISSUE THREAD

**Issue by igorkamyshev** [effector/effector#615]
## Proposal

Completely deprecate Effector usage without `scope`.

### Preamble

Let's talk about `scope` use cases.

1. Tests. Any large application will use testing.
2. SSR. Some of large applications can use SSR.

And `scope`-less use cases:
1. Fast prototype, skip `useEvent`-calls and other `scope` related effort.

(I could not find any other use cases for `scope`-less runtime).

### scope-less to scope-full app transition

This transition is pretty hard for any application. In common app without `scope` usage, we have a bunch of direct event and effect calls. It is hard to detect and fix. So, we should apply a lot of effort to fix it.

But any application tends to use Fork API (because unit-tests).

### And so?

**I purpose to deprecate `scope`-less runtime of Effector.**

It will help people to use Effector in right-way from the beginning.

It will help team to skip a lot of effort because now we have to double any test-case: `scope`-less test and `scope`-full test.

**Comment by zerobias** [comment]
> we have a bunch of direct event and effect calls. It is hard to detect and fix

I would suggest this one:
```js
const noGlobalEvent = createEvent({scopeOnly: true})
noGlobalEvent()
// => Error: cannot call event "noGlobalEvent" without scope
```

**Comment by AlexandrHoroshih** [comment]
If not completly drop scope-less support, maybe this could be something like [`configure`](https://mobx.js.org/configuration.html) then? 🤔 

```ts
// app entrypoint.ts
import { globalConfigure } from "effector"

globalConfigure({
 forceScope: true,
 blockCycles: false,
 ...
})
```

**Comment by zerobias** [comment]
If the part of the application that controls dynamic styles makes a forbidden call, where should an exception be thrown so that the part of the application responsible for the order form is not affected?

**Comment by igorkamyshev** [comment]
I mean, why someone should use Effector without Fork API? What is the use case?

**Comment by igorkamyshev** [comment]
Ok, we've discussed it in the chat. Idea wasn't good enough 🤗
