### ISSUE TITLE
`sample` doesn't infer types for `fn` in 22.2.0

### ISSUE THREAD

**Issue by igorkamyshev** [effector/effector#616]
**What is the current behavior:**

TypeScript error
```
Type '(value: never) => ReceiverEmailError | null' is not assignable to type '((src: string, clk: void) => any) & ((value: never) => ReceiverEmailError | null)'.
  Type '(value: never) => ReceiverEmailError | null' is not assignable to type '(src: string, clk: void) => any'.
    Types of parameters 'value' and 'src' are incompatible.
      Type 'string' is not assignable to type 'never'.
```

**Please provide the steps to reproduce and if possible a minimal demo of the problem via https://share.effector.dev, https://codesandbox.io or similar**

https://codesandbox.io/s/typescript-playground-export-forked-k5e24?file=/index.ts

**What is the expected behavior:**

No errors. 

**Which versions of effector packages, and which browser and OS are affected by this issue? Did this work in previous versions of effector?:**

Effector 22.2.0

**Comment by igorkamyshev** [comment]
There are no errors in 20.0.6 ☄️

**Comment by zerobias** [comment]
[Cannot reproduce](https://www.typescriptlang.org/play?ts=4.5.4#code/FASwtgDg9gTgLgAgN4IMYwKYEM4YKIBuGAdnADRqY4YDKcsGFAzlpADYYIC+CAZjFDAIA5Bl68MqejGHBgqKMSaIMYLCDYA1LGxAATHCEUAxEJj0IAvJWy5CJOAAoAlPMXKEq9WwBCbAK4w5lY21PakLm5KiAAkXhoh6La00hiOwsKuwCT+QgBKkhggRDB4ahp4QbDIwAgIBQCO-mYYFtbCmE0tesJktQgA6gLEAOZl3iHCAO7DIwD68Wy9wFxyCtEIceVslQIwiVS4dAwAPAWoRSXjFVX7AD4IxP5sbAB8jk8vWXAAnhCc2l0BmkNBAI2IOECnGsJ0B-gw7wIOnhAC4EHCMM4rK8EAAjKBQDhYYgAbjW7kQWAgEDYP0B+kMiis-ROu1gABU-ox0ciEY4kUDGcQALJUtEAbXpwNgoPBkMwFDZME5-wAuuLVVjLK9+vzeWiMc40UqVZwHp82NjHs82GSoh5Os1zAadAyQWCIXAoSE9QFMVa4DB4Xb1h4wCBiAAZEgjOAAC3ZUygLsF7rlXswPoF8K1OrqgeDchY7DSSH6qDYUFQAGsJYspULTOYKIs-IFzKq+nUmFBAhc0VtvF2+MQ0VSaXTXcCjMRHOL+nVxY7uhRzpcMKVtkqAHSNJ2tTsLhDi8NRmPxxNQVeFYob647W7boaKMbbQ91TXDuBYGAjDBwAdFiVPouFcIA) in typescript v 4.5.2/4.5.4, this is an issue in older typescript versions

**Comment by igorkamyshev** [comment]
I'm sorry, but right in my reporo it's TS 4.5.4 and Effector 22.2.0. Am I wrong?

<img width="1552" alt="Screenshot 2022-02-02 at 18 11 20" src="https://user-images.githubusercontent.com/26767722/152170242-af42bb22-69af-4db5-b489-fd06f8d0f1cb.png">

**Comment by domosedov** [comment]
> I'm sorry, but right in my reporo it's TS 4.5.4 and Effector 22.2.0. Am I wrong?
> 
> <img alt="Screenshot 2022-02-02 at 18 11 20" width="1552" src="https://user-images.githubusercontent.com/26767722/152170242-af42bb22-69af-4db5-b489-fd06f8d0f1cb.png">

At the bottom right of the screenshot, the version is indicated - 4.4.4, maybe this is the problem?

**Comment by igorkamyshev** [comment]
Lol. I'm lunkhead.
