### ISSUE TITLE
Store is derived incorrectly

### ISSUE THREAD

**Issue by alatielle** [effector/effector#620]
**What is the current behavior:**

The store is incorrectly derived from other stores through a series of transformations (demo below).
https://share.effector.dev/Ze5xwlZg

**What is the expected behavior:**
See comments in the demo

effector@master, mac os, firefox

**Comment by sergeysova** [comment]
@alatielle https://share.effector.dev/Ks0hB3sb

It is an actual date, but REPL cannot print Date object at the moment

**Comment by sergeysova** [comment]
Is there any other problems with derived store?

**Comment by sergeysova** [comment]
Closing this, as a result of a private conversation. This is not an effector bug actually
