### ISSUE TITLE
warning occurs in webstorm inspections when trying to assign sample to a variable in v22.2.0

### ISSUE THREAD

**Issue by uulaal** [effector/effector#624]
There was no such warning in prev version: 
![image](https://user-images.githubusercontent.com/38786565/152233038-41f2636f-672c-425a-88ed-e62c02aa0276.png)

Seems like it's caused by adding `void` instead of `never` in sample typings

**Comment by zerobias** [comment]
Yes, it is, but this is a valid type, so there should be no void return. Is webstorm’s fork of typescript handle this case at all?

Would you like to replace void returns with never and check, please? Open `node_modules/effector/index.d.ts`, select [SampleRet](https://github.com/effector/effector/blob/master/packages/effector/index.d.ts#L1143:L1340) and replace all void occurrences with never

**Comment by uulaal** [comment]
Yeah, it's valid, seems like it's bug inside of WS or WS's typescript. Replacing void with never helps and doesn't break anything

**Comment by sergeysova** [comment]
@zerobias @uulaal Is it still actual?
Looks like it solved, isn't it?

**Comment by SQReder** [comment]
Still an issue.
 WebStorm 2022.2.3
Build #WS-222.4345.14, built on October 5, 2022
TS 4.8.4

**Comment by AlexandrHoroshih** [comment]
@SQReder which version of effector you have?

 Fix was added in the effector@22.3.0

**Comment by SQReder** [comment]
Sry, thought it was fixed in webstorm
