### ISSUE TITLE
Guard documentation

### ISSUE THREAD

**Issue by olegKusov** [effector/effector#636]
In documentation about guard there is no info that if we do not pass 'source' then guard gets data from clock.

Moreover, we can add to Docs more cases like that 
https://share.effector.dev/deTs17ML

**Comment by sergeysova** [comment]
Fixed in https://github.com/effector/effector/commit/00a67a2d204f99b952a3e9bcf05af18d812929a4 https://github.com/effector/effector/commit/b976212ed89622a011d26ed5fa5415416c9db937
