### ISSUE TITLE
How to pre-fill scope?

### ISSUE THREAD

**Issue by smenshikov** [effector/effector#642]
Will try to describe my case in terms of Next.js. 
I use Next.js and this is `getInitialProps` function from `_app` file
![telegram-cloud-photo-size-2-5332791240967699307-y](https://user-images.githubusercontent.com/75778692/160370918-16fa3a02-bc95-4a12-8ba9-1408a4bcd6f5.jpg)
The `getInitialProps` function starts when page route is changed, it is a fact. So, I would like to setup initial state of scope like this
```
const scope = fork({
  values: [
    [$user, {id: 1, userName: 'test', ...}]
  ],
})
```
to avoid calling of `getMeFx` each time when page changes. 
I understand that **fork API** has `values` field as in example, but I dont understand how I should save the user data `{id: 1, userName: 'test', ...}` for initial state of scope.

Hope this makes sense!

**Comment by sergeysova** [comment]
You can do this like this:

```js
const newScope = fork({ values: serialize(oldScope) })
```

**Comment by smenshikov** [comment]
@sergeysova Pretty simple solution. Thank you so much!
