### ISSUE TITLE
useStoreMap is broken with React 18.

### ISSUE THREAD

**Issue by mendrik** [effector/effector#643]
**What is the current behavior:**
With react 17 everything is fine, with react 18 (which was just released) useStoreMap doesn't work.
```typescript
const works = useStore($myStore)
const doesntWork = useStoreMap($myStore, x => x)
```
**What is the expected behavior:**
`works` and `doesntWork` should give the same result, since useStoreMap uses identity function as mapping.

**Which versions of effector packages, and which browser and OS are affected by this issue? Did this work in previous versions of effector?:**
```
effector: 22.2.0
effector-react: 22.0.6
```

**Comment by mendrik** [comment]
btw. not sure if this could simplify the react package but v10 offers now this:

https://github.com/reactwg/react-18/discussions/86

**Comment by AlexandrHoroshih** [comment]
Hello @mendrik !

I just have added test on your example [here](https://github.com/effector/effector/pull/655/commits/6f807719af9e67ba87ac3b9e23bec25e76d735bf), but it's successful both with `react-17` and `react-18` 🤔 

Do you have more detailed example on what did not work for you with `react-18` and `effector-react`?

**Comment by mendrik** [comment]
@AlexandrHoroshih I can only demonstrate it via screenshots:
![image](https://user-images.githubusercontent.com/160805/162685430-75e565ff-381c-4e6c-91f6-342f3488ade4.png)

and I get the following log, so the problem definitely exists:

![image](https://user-images.githubusercontent.com/160805/162685587-9959af2a-4c8a-4161-978f-a1d0ae1cbda5.png)

Same code, same mapping, only difference is useStore vs useStoreMap

**Comment by mendrik** [comment]
If you need help debugging it, I could have a google meet to demonstrate it

**Comment by cqh963852** [comment]
https://codesandbox.io/s/adoring-smoke-w7ipvn?file=/src/index.tsx
 
Meeting the same problem. useStoreMap not working under react18 StrictMode

**Comment by mendrik** [comment]
for those who cannot wait for a fix here is a quick hack. Change your import to use this local hook instead. 

```typescript
import { Store } from 'effector'
import { useStore } from 'effector-react'

// this is a hack until effector fixes react 18
export const useStoreMap = <State, Result>(
  store: Store<State>,
  fn: (state: State) => Result
): Result => fn(useStore(store))
```

**Comment by mendrik** [comment]
btw. this is still broken in "effector-react": "22.3.0", the test somehow doesn't replicated exactly my circumstance. But I'm not doing any magic, just using stores and some sample() calls

**Comment by AlexandrHoroshih** [comment]
🤔 

Is it all your cases of useStoreMap that are broken, or this specific one?

**Comment by AlexandrHoroshih** [comment]
Also, which React you using in your case?

**Comment by mendrik** [comment]
```
    "effector": "22.3.0",
    "effector-logger": "0.13.4",
    "effector-react": "22.3.0",
    "fantasy-land": "5.0.0",
...
    "react": "18.2.0",
    "react-dom": "18.2.0",
```

As far as I can tell all instances of useStoreMap are broken, the moment I replace it with that manual map (previous comment) everything works fine.

`<StrictMode>`  on or off seems to make no difference.

**Comment by AlexandrHoroshih** [comment]
@mendrik can you show some more examples, where `useStoreMap` doesn't work? Does it matter, if it is config shape or default shape of the hook?

I didn't manage to reproduce your `useStoreMap` bug - not in tests, not in my project at work, which has React 18 and bunch of `useStoreMap` cases, so it must be something else

**Comment by mendrik** [comment]
@AlexandrHoroshih I wonder how we could do this, I have a relatively big project, would you have time for a google meet? I'm not sure how to even start to make a small reproduceable example from my codebase.

**Comment by mendrik** [comment]
I'm closing this for now, I have refactored my code a bit and I'm not really sure what I changed at this point, but useStoreMap behaves correctly. I will reopen this when the bug comes back or I have a reproducable example
