### ISSUE TITLE
createEffect not work with react18

### ISSUE THREAD

**Issue by cqh963852** [effector/effector#645]
Here is the demo.
https://codesandbox.io/s/zen-torvalds-ov7vun

The count works fine. But createEffect seems not work.

![image](https://user-images.githubusercontent.com/17702287/161483045-52148574-dc9f-4d89-bf07-949b446adf86.png)

**Comment by zerobias** [comment]
You need to pass `fetchUserFx` through `useEvent` too, it was just called outside of your scope. I [updated your example](https://codesandbox.io/s/great-shaw-ly63f2?file=/src/App.tsx:1331-1342), everything worked as expected

```js
const handler = useEvent({inc, dec, fetchUserFx})
...
onClick={() => {
  handler.fetchUserFx(
```

Unfortunately, we can't show a warning for that kind of situations yet, but we working on it, as this is happens with users from time to time

**Comment by sergeysova** [comment]
@cqh963852 would you like to send PR?
