### ISSUE TITLE
Binding for `SolidJS`

### ISSUE THREAD

**Issue by igorkamyshev** [effector/effector#658]
## Proposal

Add new package `@effector/solid` with helpers (`useStore`, `useEvent`) for connecting Effector and [SolidJS](http://solidjs.com/).

## Use case

1. SolidJS is getting more popular.

<img width="1330" alt="Screenshot 2022-04-11 at 13 20 39" src="https://user-images.githubusercontent.com/26767722/162676605-ebe558b1-5d59-4cf7-b93f-f7342f29b2fb.png">

2. SolidJS is a really great way to build interfaces, but the internal reactivity system is pretty limited. So, we can improve DX for every developer who uses SolidJS.

P.S. This issue is for progress tracking, I'm going to write this bridge in a couple of weeks.

**Comment by AlexandrHoroshih** [comment]
I was playing around with solid.js + effector a while ago:
https://stackblitz.com/edit/node-jkntpd - working example with react-like hooks for effector integration into solid.js

I'm not sure that it is the best way to build api for solid, though 🤔

**Comment by sergeysova** [comment]
I propose to name package like any other bindings: `effector-solid`
