### ISSUE TITLE
Serialize createGate's stores console errors

### ISSUE THREAD

**Issue by domosedov** [effector/effector#672]
**What is the current behavior:**
console error `There is a store without sid in this scope, its value is omitted`

**Please provide the steps to reproduce and if possible a minimal demo of the problem via https://share.effector.dev, https://codesandbox.io or similar**
[stackblitz](https://stackblitz.com/edit/github-fnryrg?file=pages%2Findex.js)

**What is the expected behavior:**
No errors
Maybe add optional sids to createGate' stores and process with babel-plugin?

```js
let MyGate = createGate({
  sid: 'my-sid'
})
```

**Which versions of effector packages, and which browser and OS are affected by this issue? Did this work in previous versions of effector?:**

```js
"effector": "^22.3.0",
"effector-react": "^22.0.6",
"next": "latest",
"react": "^17.0.2",
"react-dom": "^17.0.2"
```

**Comment by sergeysova** [comment]
Reproduction https://share.effector.dev/ofScWoE7
