### ISSUE TITLE
Add readonly stores on type level

### ISSUE THREAD

**Issue by zerobias** [effector/effector#676]
## Proposal

Allow users to export store as readonly unit: explicitly forbid usage of that store in `target` and hide its `.on` method

## Use case

Module encapsulation: ensure that store is changed only through curated set of events — public exported api of that module

**inc.ts**
```ts
import {createStore, ReadonlyStore} from 'effector'

export increment = createEvent()

export const $closed: ReadonlyStore<number> = createStore(0)
  .on(increment, n => n + 1)
```

**app.ts**
```ts
import {$closed} from './inc'

$closed.on
// Error: method 'on' is not found on $closed

sample({
  clock: createEvent(),
  target: $closed
})
// Error: {message: 'Readonly store cannot be used as a target'; target: $closed}
```

**Comment by AlexandrHoroshih** [comment]
Looks like mapped/derived units must be readonly by default? 🤔 
Along with runtime validation and changes

**Comment by sergeysova** [comment]
What about to make `.map()` returns `ReadonlyStore<T>`?

And for convenient usage we can add `.readonly(): ReadonlyStore<T>`.
Usage:

```ts
const $counter = createStore(0)

// public api
export const $counterRead = $counter.readonly()

// logic
$counter.on(counterChanged, (_, counter) => counter);
```

Or, users can define the're own `public.ts` file, like @Kelin2025 do:

```ts
// model.ts

export const $counter = createStore(0)
```

```ts
// public.ts

import * as model from './model'

export const $counter = model.$counter.readonly();
```

**Comment by zerobias** [comment]
> What about to make .map()

Breaking change to `.map` is pretty obvious move, so it not make this idea further, we are not ready to discuss maps

> And for convenient usage we can add .readonly()

Conventions should not force useless runtime code, let's focus on types and terms here

**Comment by sergeysova** [comment]
`Store<T>` — can be used as a source/clock and target
`StoreSource<T>` — can be used only as a source/clock
`StoreTarget<T>` — can be used only as a target

`Event<T>` — can be used as a source/clock and target
`EventSource<T>` — can be used only as a source/clock
`EventTarget<T>` — can be used only as a target

Potentially can be changed in the `effector 23.0`

```ts
event.map(): EventSource<T>
event.prepend(): EventTarget<T>

store.map(): StoreSource<T>
```

**Comment by ein1x3x** [comment]
Maybe just add seal() method? Optionally pass parameters what exactly to seal. Forcing runtime code for conventions is not a good idea (maybe) but it also will help to prevent unexpected behaviour where it's needed.

```
const $something = createStore(...).on(...).seal();

$something.on(); // error

// or 

const $something = createStore(...).on(...).seal(['on', 'target']);

sample({
...,
target: $something
})
```

**Comment by zerobias** [comment]
> StoreSource<T> — can be used only as a source/clock

Preventing that code

```ts
const $foo: Store<T>
sample({
  clock: $foo,
  target: bar,
})
```

means that update of the $foo has no unexpected consequences (because you can’t add more subscribers to $foo)

While preventing that code

```ts
source({
  clock: some,
  source: $foo,
  target: bar,
})
```

means that we can’t access current value of the $foo at all, it’s entirely private. Whoever this _does not_ imply that we can’t send new values to $foo!

It’s another independent use case:
```ts
sample({
  clock: some,
  target: $foo
})
```
It’s important because you can update value of the $apiToken but you shall not be able to read it

So we have three properties:
1. Ability to add new consequences (support use in clock)
2. Ability to silently read current value (support use in source with given clock)
3. Ability to add new triggers or change current value  (support use in target)

**Comment by zerobias** [comment]
If you wonder why this feature didn’t implemented earlier then now you see that. It is not a dilemma like be or not to be, this is an object with three independent boolean properties for which we haven’t meaningful vocabulary yet

**Comment by Lonli-Lokli** [comment]
I would like to upvote this part - `add .asReadonly()` - because sometimes when you are exposing store it's useful to have it as readonly. And useless - `.map(_ => _)` is just not dev-friendly.
