### ISSUE TITLE
state is not updated in the component when we call event on the client

### ISSUE THREAD

**Issue by Musho-T** [effector/effector#677]
the project is written in React + SSR

```ts
import { useEvent, useStore } from 'effector-react/ssr';
```

when we fetch from 'effector-react/ssr' the state is updated but this option doesn't work

```ts
sample({
  clock: submitDataFx.doneData,
  fn: () => true,
  target: toggleModal,
});
```

but console.log in reducer works

````ts
const $showModal = domain
  .createStore<boolean>(false, {
    sid: '$showModal',
  })
  .on(toggleModal, (state, payload) => {
    console.log(payload);
    if (typeof payload !== 'boolean') {
      return !state;
    }
    return payload;
  });
````

works fine without  'effector-react;
 import { useEvent, useStore } from 'effector-react';

```json
    "effector": "22.2.0",
    "effector-react": "22.0.6",
    "react": "17.0.2",
    "vite": "2.8.4",
```

**Comment by sergeysova** [comment]
Looks like you called the event without scope.
Maybe you forgot some event wrap to `useEvent`?

**Comment by Musho0** [comment]
[sergeysova](https://github.com/sergeysova) yes it worked) thank you very much
