### ISSUE TITLE
Track if scope is settled

### ISSUE THREAD

**Issue by AlexandrHoroshih** [effector/effector#687]
## Proposal

I suggest to extend `allSettled` api like this:
```ts
const scope = fork()

allSettled(scope) // Promise, which will be resolved, once there is no pending calculations in this scope
```

## Use case

In some cases there is a need to track, if there are pending effects (like requests) before some action - e.g. before route transition

Something like this:
```ts
const onLinkClick = () => {
 allSettled(currentScope).then(() => {
   router.push(...)
 })
}
```

**Comment by zerobias** [comment]
Released in effector 22.5.0
