### ISSUE TITLE
migrate to useUnit from useStore and useEvent in effector-vue

### ISSUE THREAD

**Issue by ilajosmanov** [effector/effector#713]
For consistency, my proposal is to migrate to useUnit also (like in react)
`useStore -> useUnit`
`useEvent -> useUnit`
`useVModel -> useUnit($store, {mutable: true})`

Related #680

**Comment by sergeysova** [comment]
@ilajosmanov What do you think not to merge `useVModel` with `useUnit` at this stage of discussion?

It should be very simple method at the first implementation, I think

**Comment by ilajosmanov** [comment]
@sergeysova yes, probably you are right

**Comment by igorkamyshev** [comment]
Done in https://github.com/effector/effector/pull/1003, will be released in Effector 23.

Depredations for `useStore`/`useEvent` will be introduced later.

`useVModel` is a great function in my opinion, and it should not be merged to `useUnit` because it has a different semantic.
