### ISSUE TITLE
Replace `list.flat()` with `Array#concat` for compatibility build

### ISSUE THREAD

**Issue by demark** [effector/effector#714]
Hi,

I've been working on a legacy build for IE11-like environment and noticed that [compat](https://unpkg.com/effector@22.3.0/compat.js) build has ES2019 `Array#flat()` invocation to flatten the nodes. 

After briefly looking at the source code, it was clear that IE11 compatible build requires a few things to be polyfilled, specifically: `Promise` and `Object.assign`, which are either way broadly used in application code. But presence of ES2019 `Array#flat()` was a bit unexpected due to uncommon use in compat builds. It could be replaced with a slightly more verbose ES5 version.

**[Current](https://github.com/effector/effector/blob/b4e9f4411fc9412d1264d90a70165716820849d3/src/effector/createNode.ts#L11):**

```js
(Array.isArray(list) ? list : [list]).flat().map(getGraph)
```

**Proposal:**

```js
Array.prototype.concat.apply([], Array.isArray(list) ? list : [list]).map(getGraph);
```

Evidently, `.flat()` looks more concise, but requires one more thing to polyfill.

Also, I think it would be helpful to explicitly mention in the documentation about `Promise` and `Object.assign` to be polyfilled for IE11 compat build to run.

**Comment by zerobias** [comment]
We explicitly mentioned polyfills which you need alongside compat module in [documentation](https://effector.dev/en/introduction/installation/)
