### ISSUE TITLE
Do not use `sid` as a key in effect handler mocking

### ISSUE THREAD

**Issue by igorkamyshev** [effector/effector#719]
## Proposal

Do not use `sid` of effect as a key while replacing handlers during fork. Since effects are not transferred between environments, we can use any un-serializable value as a key. e.g., effect object itself.

A drawback is availability of Map (which is required for this change) in some legacy browser (`effector/compat`). However, we recommend installing several polyfills to make this bundle works. I assume, we can add one more polyfill to this list.

## Use case

The main use case is effects with the same `sid`. They can exist due to imperfection of babel plugin (nested objects with factories, high order factories, etc.). In this case, replacement by `sid` causes replacement of different effect handler. Example:

```js
funcioon createEffectFactory(store, log) {
  const effect = createEffect(p => console.log(log, p))
  return (id) => attach({ source: store, mapParams: (_, s) => s[id], effect })
}

const firstFx = createEffectFactory($data)('name')
const secondFx = createEffectFactory($data)('age')

const scope = fork({ handlers: [
  [firstFx, () => console.log('OTHER')]
] })

allSettled(secondFx, { scope }) // OTHER
// due to the same sid, secondFx does not have original handler
```

**Comment by AlexandrHoroshih** [comment]
I would suggest to do the same for stores too - this way we could allow users do not setup babel-plugin for tests 🤔

**Comment by sergeysova** [comment]
> I would suggest to do the same for stores too

How it should work with scope restoration?

```ts
const scope = fork({ value: window.VALUES })
```

**Comment by AlexandrHoroshih** [comment]
I think, it can be different mode depending on provided `values`:
- `Record<string, Json>` -> sid-based store values restoration for SSR and similar cases with more than one environment
- `Map<Store, Value>` -> store reference-based value substitution for tests and similar cases without need to transfer state between different environments

**Comment by zerobias** [comment]
Implemented some time ago
