### ISSUE TITLE
Get rid of special language

### ISSUE THREAD

**Issue by igorkamyshev** [effector/effector#721]
## Preface

I am contacting with developers who are just starting working with Effector for two years. Commonly, they have two major misunderstandings about this technology: declarative commands and special language.

Declarative commands are the heart of Effector, and it gives a huge advantage after initial introduction. It's hard, but it's worth.

Special language (`sample`, `clock`, etc.) seems like a historical attribute of the Effector. It is new concepts for developers, and we must give a description of it every time.

> Yeah, `clock` is like trigger. Yep, this operator executes after `clock` call. You know, it is analogue from electricity, you should read some wiki atricles about it.

Since Effector position slightly moved from “the state manager” to “business logics with ease” I think we should aim to simplify language of Effector and move it closely to business logic language.

Let's see a pretty common case. Business rule is “when URL changed, take some context and if it's necessary to fetch new page, cancel all previous fetching and perform fetching of new page”. This rule can be easily transformed to Effector operator 👇 

```ts
sample({
  clock: changePage,
  source: $commonContext,
  filter: $needPage,
  fn: (page, ctx) => ({ ...page, ...ctx }),
  target: [cancelAppPendingRequests, fetchPageUrlFx],
})
```

It's pretty easy to read, but let's go deeper 👇 

```ts
// fetching rule
sample({
  // when page changes
  clock: changePage,
  // take common context
  source: $commonContext,
  // if need new page
  filter: $needPage,
  // tramsform context
  fn: (page, ctx) => ({ ...page, ...ctx }),
  // then
  target: [cancelAppPendingRequests, fetchPageUrlFx],
})
```

So, these comments could describe the entire process to a developer who is not familiar with Effector language. What if we omit specific language and left only these comments? Let's see 👇 

```ts
rule({
  when: changePage,
  take: $commonContext,
  if: $needPage,
  transform: (page, ctx) => ({ ...page, ...ctx }),
  then: [cancelAppPendingRequests, fetchPageUrlFx],
})
```

Now all comments are useless because our code describes the business process.

## Proposal

I purpose to the following steps:
+ `rule` with the interface like `rule({ when, take, if, transform, then })` as an alias for `sample`
+ extends `rule`-operator to replace split  with something like `rule({ when, take, choose: { caseName: { if, transform, then } })`

After a couple of years of adopting, we can deprecate specific language and simplify Effector usage.

> These API-s are just examples. I do not think we can use as is.

## Drawbacks

Foremost, it's a new language and I think we should carefully discuss the API of it.

Furthermore, developers who are already familiar with a specific language of Effector will suffer (a bit).

As I understand, TypeScript won't allow `step 2` right now.

## Afterword

This RFC was born in a discussion with @AlexandrHoroshih about source code of Aviasales web interface.

**Comment by AlexandrHoroshih** [comment]
As a counter-argument - i find kind of useful that (after stage of adoption and getting used to it) "effector language" allows to describe e.g. "when" and "reason" in one universal word "clock" in discussions with colleagues

e.g. instead of
> _"when logicStepDone event is happened, then fetchDataFx happens, but only if $fetchAllowed is true"_

or 

> _"logicStepDone event is the reason for fetchDataFx, if $fetchAllowed is true"_

one can say

> _"clock is 'logicStepDone', filter is $fetchAllowed and target is fetchDataFx"_

This still causes friction with new-to-effector teammates, but overtime it kinda works (at least for me)

**Comment by sergeysova** [comment]
Effect has much documentation, and user content about current API.
If we change it these hude work will be obsolete and we'll need to recreate them.

I don't think we need to focus on a new name changes (after moving to sample from guard, and recommending to use sample over the forward). I think the main focus in the effector is a documentation and guides.

Each library has its own language: redux (selectors, reducers, action), rxjs, react(hooks, props, controlled/uncontrolled,...). It is ok if we need to use some words to name some entity.

**Comment by igorkamyshev** [comment]
> Effect has much documentation, and user content about current API. If we change it these hude work will be obsolete and we'll need to recreate them.
> 
> I don't think we need to focus on a new name change (after moving to sample from guard, and recommending to use sample over the forward). I think the main focus in the effector is a documentation and guides.
> 
> Each library has its own language: redux (selectors, reducers, action), rxjs, react(hooks, props, controlled/uncontrolled,...). It is ok if we need to use some words to name some entity.

People do not read documentation. 

Yes, but `redux`, `rx`, `react` do not call themselves as a “business logic manager”. If Effector is aiming to be “business logic manager” the language must emphasize it. No one uses `sample` and 'clock' in business rules.

**Comment by sergeysova** [comment]
> People do not read documentation.

This is not the reason to change the main API to a totally different.

> No one uses sample and 'clock' in business rules. 

No one uses convention "what words to use to describe business logic". In the most cases there is natural language

**Comment by igorkamyshev** [comment]
> No one uses convention "what words to use to describe business logic". In the most cases there is natural language

It's the reason, why I suggest to introduce API closer to natural language.

**Comment by sergeysova** [comment]
Maybe get rid of javascript there?
No one programming language can correctly describe natural language.
