### ISSUE TITLE
`useUnit` object form adds `(payload: void) => void` for `Event<void>` instead of `() => void`

### ISSUE THREAD

**Issue by igorkamyshev** [effector/effector#740]
**What is the current behavior:**

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYygUwIYzQUQG5oB28AvnAGZQQhwDka55ayM0tA3AFCiSyJwBXAM5oAqoWCkKVGvUbNWUALToMLDp07IIhIfDQFiAQTgBeFKuz4iMADx4IwACYA+ABQBKTdt3wkhCBgAeQBrODJzYTEJGDd-QNCALjgDGxMSDy4fPTgIMMiRcUk3VOMvTgBhakhCGziUDAAbRoAjNRDkgOCwjMrqnTqkZCbW9uS88PLyAUIWYB04KvAB4nrh5rbkHuShkc2OuBLDGGSZkICAd0IPMxc4B2dJxE44V7gAene4MAwhIU4SJogA

```ts
import { createEvent } from 'effector';
import { useUnit } from 'effector-react';

const eventA = createEvent<void>()

const { notOk } = useUnit({ notOk: eventA });
const ok = useUnit(eventA)

Component({ callback: notOk })
Component({ callback: ok })

function Component({ callback }: { callback: (event: unknown) => void }) {
    // ...
}
```

**What is the expected behavior:**

Same behaviour in object form and in simple form, no error. It is current behaviour of `useEvent`

**Which versions of effector packages, and which browser and OS are affected by this issue? Did this work in previous versions of effector?:**

`effector-react` with `useUnit`

**Comment by sergeysova** [comment]
> Note: it is the same bug for `Effect<void, any, any>`

**Comment by domosedov** [comment]
Not fixed if using effector-react/scope
[tsplay](https://www.typescriptlang.org/play?ssl=14&ssc=2&pln=1&pc=1#code/JYWwDg9gTgLgBAbzgYygUwIYzQUQG5oB28AvnAGZQQhwDka55ayM0tA3AFCiSyJwBXAM5oAqoWCkKVGvUbNWUALToMLAPRDkEMGg6dO2wkPhoCxAIJwAvClXZ8RGAB48EYABMAfAAoAlAZGJvyEEDAA8gDWcGS2wmISMD5IoRGRAFxwZk5WJH5cQfAQ0XEi4pI+2ZYBnADC1JCETskoGAA2bQBGahlwqVExAfXgEE3ELcjtXT2ZxYMG5AKELMCjcMONzUiTHd3I0SSZ21N7vZXmMJlLkaEA7oR+Nl5wbp6DiJxwX3Dq6nBgGCEQk4JAMQA)

**Comment by sergeysova** [comment]
@domosedov It is looks like fix is not released to NPM yet

**Comment by domosedov** [comment]
@sergeysova 
https://stackblitz.com/edit/react-ts-ht7wlq?file=package.json,App.tsx

**Comment by sergeysova** [comment]
@domosedov It is released in https://github.com/effector/effector/releases/tag/effector-react%4022.1.1

**Comment by sergeysova** [comment]
@domosedov Released in the https://github.com/effector/effector/releases/tag/effector-react%4022.1.5
