### ISSUE TITLE
Custom entries in Domain

### ISSUE THREAD

**Issue by igorkamyshev** [effector/effector#758]
## Proposal

Add possibility to store custom entries in Domain.

Examples of custom entries:
- `Gate` from `effector-react`/`effector-vue`
- `Route` from Atomic Router
- `Query` from Farfetched

In can be done by some API in `createDomain` 👇 
```ts
// app.ts
const domainWithRoutes = createDomain({ entries: ['route'] }); // Domain<'route'>

const profileRoute = createRoute({ domain: domainWithRoutes })

domainWithRoutes.customEntries.onCreate('route', (route) => /* */)
domainWithRoutes.customEntries.history('route') // Array<Route>

// create-route.ts
functrion createRoute({ domain }: { domain?: Domain<'route'>}) {
  const route = /* ... */

  domain.addCustomEntry('route', route);
}
```

## Use case

1. Farfetched DevTools. I'm going to create some UI to debug Queries in dev-mode. To display all Queries, I have to store it somewhere, so Domain seems like a perfect match for this purpose.
2. Extended logging for non-standard entries. It could be important to track all created Routes/Queries to set up monitoring on server-side while SSR.

**Comment by zerobias** [comment]
In general, data exchange takes place through pure graph nodes, for example one library exports `createNode({
  meta: {
    formField: 'age',
    inputType: 'number',
  }
})` and passes updates through it, while the other one, which understands the protocol of the first one, picks up the node and creates `<input type="number" />` based on it.

**Comment by igorkamyshev** [comment]
> In general, data exchange takes place through pure graph nodes, for example one library exports `createNode({ meta: { formField: 'age', inputType: 'number', } })` and passes updates through it, while the other one, which understands the protocol of the first one, picks up the node and creates `<input type="number" />` based on it.

I got it, so I will try this approach on Farfetched and show the results there.

**Comment by igorkamyshev** [comment]
It is not necessary since @AlexandrHoroshih is working on Inspection API 🤗
