### ISSUE TITLE
Watch call order

### ISSUE THREAD

**Issue by asdennie** [effector/effector#771]
When using: 
```ts
const source = createEvent()
const target = createEvent();

source.watch(() => {
  console.log("first called");
  target("called from one");
  console.log("first finished");  
})
source.watch(() => {
  console.log("second called");
  target("called from two");
  console.log("second finished");  
});
target.watch(console.log);
source();
```
I would expect to have the result: 
```
first called
called from one
first finished
second called
called from two
second finished
```
But instead I get: 
```
first called 
second called 
called from one 
called from two 
second finished 
first finished 
```

Is this by design? For now I use `setTimeout` to call the `target` effect to get my expectation. 
Example: https://share.effector.dev/zMi03bGW

**Comment by sergeysova** [comment]
Also, do not call events from `.watch` callbacks.
Use `sample` for this.

```ts
sample({
  clock: source,
  target: target,
})
```

**Comment by sergeysova** [comment]
> Is this by design?
Yes, this is expected behavior. But if you don't rely on this, this isn't the case

**Comment by asdennie** [comment]
Thanks for the feedback, I use watch on mount of a component and use component props to trigger another event. It's clear to me now not to call events from watch. I have bad development experience when using `hmr` and `sample`, for example: 
```
const source = createStore(0);
const target = createEvent();
const e = sample({source,target})
import.meta.hot.dispose(() => clearNode(e)); // target is not triggered any more
```
To get this working I do: 
```
const source = createStore(0);
const target = createEvent();
const e = sample({source})
import.meta.hot.dispose(forward({from: e, to: target})); 
```
But `forward` is deprecated now. I know there's a separate issue for hmr, but this is some dev ux. 
Maybe I am doing something wrong, or you have some tips..  let me know.
