### ISSUE TITLE
How to increase DX when using factories

### ISSUE THREAD

**Issue by WoodenPC** [effector/effector#777]
Hi. In my project  I have react components in features folder, each feature has its own fabric with stores. 
features/feature1/model/feature1.factory.ts
features/feature2/model/feature2.factory.ts ...etc (One page can have multiple `<Feature1 /> and <Feature2 />`)

Also i have some utility fabrics in my shared folder

For all that fabrics i need to add paths to them to babel plugin to generate correct sid. This is so frustrating. My babelrc file grows every time i add new factory to my project. Maybe there are some best practices which i am missing ?

**Comment by sergeysova** [comment]
Hello @WoodenPC.
You can add the path to your feature into the babel plugin, then just reexport factories from `index.ts`

```ts
// features/some-name/index.ts
export { someFactory } from './models/some-factory.ts'
export { anotherDeal } from './models/another-deal.ts'
```

```json5
// babelrc or babel.config
{
  "plugins": [
    ["effector/babel-plugins", { "factories": ["src/features/some-name"] }]
  ]
}
```

```ts
// pages/welcome/model.ts
import { someFactory, anotherDeal } from 'features/some-name'

someFactory()
anotherDeal()
```

**Comment by WoodenPC** [comment]
@sergeysova thanks, however i have more questions about babel plugin :)

in my project i have path aliases. Some factory placed in src/shared/lib/sharedFactory  (naming for example), in plugin i wrote 
```
factories: [
      'src/shared/lib/sharedFactory ',
  ],
```

In other parts of code i import that factory with path alias `import {createFactory} from 'shared/lib/sharedFactory'` . sids for factory not creating correctly until i change in babel plugin path to 'shared/lib/sharedFactory' . Is that normal ?

And if i want to use factory inside my react component e.g.
```
const MyComponent= () => {

  const [model] = useState(factory());
  
  ...do something with model units inside useEffects, callbacks etc

return ....
}
 
```

and use <MyComponent /> <MyComponent /> twice inside page render , will i have correct sids ? And how to generate sids with such libraries as effector factorio which gives us helpers for wrapping factories.

**Comment by WoodenPC** [comment]
or maybe its a bad practice to call fabrics inside react components ? If so, please can you provide example how to handle such cases when we need separate model for each component ?

**Comment by AlexandrHoroshih** [comment]
@WoodenPC 

You can actually add both paths to `factories` - with aliases and without
Plugin basically looks only at import paths, not at the specific modules

>  its a bad practice to call fabrics inside react components ?

It is indeed a bad practice. It is recommended to move to a key-value approach instead:
- represet your data in the models as key-value records `{ [key: string]: value }` and in stores
- use keys when you work with specific items
Example:
https://share.effector.dev/und9E3ao

More advanced solution for key-value is being developed, but this featue is quite complicated and will be done "when its done":
https://github.com/effector/effector/discussions/664#discussioncomment-2598800

**Comment by WoodenPC** [comment]
@AlexandrHoroshih thank you for help! Its sad that we cant create individual model for each components without key value.   At first sight this approach looks not flexible. Because we have to create some unique id for each component. If you have time please can you add info into documentation about this restrictions.
