### ISSUE TITLE
Forest leaks memory

### ISSUE THREAD

**Issue by noevents** [effector/effector#800]
**What is the current behavior:**

Effector/forest has a big memory problem. It builds large trees of objects while rendering anything ~~and doesn't clean up after unmounting elements~~ (edit: it takes some time for the garbage collector to clear). I've created an example with a list, the same as the one used in effector-inspector to show logs.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via https://share.effector.dev, https://codesandbox.io or similar**

https://codesandbox.io/s/aged-waterfall-n0ppu4?file=/src/effector-forest.js

**Which versions of effector packages, and which browser and OS are affected by this issue? Did this work in previous versions of effector?:**
Current

<img width="1040" alt="image" src="https://user-images.githubusercontent.com/12109435/194514548-3fade824-387f-4d9f-9405-bd9ee25ed4c9.png">
<img width="925" alt="image" src="https://user-images.githubusercontent.com/12109435/194514752-6e0b305b-fad2-496e-bd14-9e5821462801.png">

**Comment by sergeysova** [comment]
Hi!
Thank you for the reporting.
Have you tried to reproduce the problem without use a foliage package?

**Comment by sergeysova** [comment]
Also, to correctly record memory consumption, you need to record without any other code, which means without codesandbox.

**Comment by sergeysova** [comment]
<img width="501" alt="image" src="https://user-images.githubusercontent.com/5620073/194538063-c333dc06-d049-4a4c-b51f-ffe428ed29f6.png">
https://codesandbox.io/s/determined-brattain-np8du7?file=/src/effector-forest.js

I removed all foliage usage and recorded memory consumption in the other tab without codesandbox.

**Comment by sergeysova** [comment]
<img width="543" alt="image" src="https://user-images.githubusercontent.com/5620073/194538445-a438a0c8-59f1-4fab-a387-060c37dab705.png">

When I pressed "Fill the logs" many times…

looks actual

**Comment by YanLobat** [comment]
I guess for now this issue can be kinda resolved
https://codesandbox.io/s/optimistic-cray-i6jn2b inspector 0.10.5 is out
