### ISSUE TITLE
Bug with $store.map resulting in undefined value

### ISSUE THREAD

**Issue by azarenkovgd** [effector/effector#828]
**What is the current behavior:**

When executing this code:

```ts
import { createEvent, createStore } from 'effector';

const $exampleStore = createStore(null);
// abstract example, real world one would be something like $exampleStore.map((exampleStore) => exampleStore?.someKey)
const $store = $exampleStore.map(() => undefined);
const $derivedStore = $store.map(() => "Expected value");
```

`$derivedStore` has undefined value (instead of `"Expected value"`). Generalizing, `$store.map` allows you to put an `undefined` value into the derived `$store`, breaking the further work of the library. Example - `$derivedStore`.

**Please provide the steps to reproduce and if possible a minimal demo of the problem:**

[Link to share.effector.dev](https://share.effector.dev/rHTR008G)

**What is the expected behavior:**

Throw an exception if you try to put an undefined value into a `$store` using `.map`. 
Motivation - when passing undefined as a default argument of `$store`, effector throws exception. Generally, you expect that `undefined` value for `$store` is impossible.
Why is this not the case with `.map`?

Alternative - provide default value, which will be selected in case of `undefined`. For example, `null` (and possibly allow user to override it using new second argument of `.map`.

**Which versions of effector packages, and which browser and OS are affected by this issue? Did this work in previous versions of effector?**

I have tested this in share.effector.dev as well as in the latest version of effector at the moment (22.4.0)

**Comment by sergeysova** [comment]
@azarenkovgd It is not a bug.
When the reducer returns an `undefined` store can skip the update of the derive-store.
If the `undefined` was the first value for the derived-store, it will be its value.

**Comment by azarenkovgd** [comment]
Okay, thank you for your response.
