### ISSUE TITLE
Better support for Vite

### ISSUE THREAD

**Issue by bekos** [effector/effector#840]
First of all thx for the awesome library!

I'm using effector in a Svelte + Vite setup. Is it possible to use `effector/babel-plugin` without react, so we can take advantage of `fork` during tests?

**Comment by igorkamyshev** [comment]
Sure, you can found a complete tutorial in the docs of Farfetched 😇

https://farfetched.pages.dev/recipes/vite.html

**Comment by bekos** [comment]
@igorkamyshev Thanks for the answer. Unfortunately, `sid`s are still `null`. I'm using Vite 4, I don't know if this the issue 🤔 If it helps, I will try to create a repo to reproduce it.

**Comment by igorkamyshev** [comment]
Sure! Reproduction will help a lot 🙏

**Comment by bekos** [comment]
@igorkamyshev I created this repo https://github.com/bekos/effector-vite 
First commit is just the scaffolding of a Sveltekit demo app and 2nd commit is adding the babel & effector.

Just creating a store and logging the store's sid and short name.
This is what I get:
<img width="502" alt="image" src="https://user-images.githubusercontent.com/551595/215332959-175f2d0a-8d1d-4501-bae5-1e07fc736ebf.png">

Hope it helps 😃

**Comment by bekos** [comment]
@sergeysova I don't see a valid way to pass such option on this plugin 🤔 Shall I open an issue to their repo?

**Comment by domosedov** [comment]
1. Move your units to another file with `.ts` extension
```ts
// model.ts
export const $myStore = createStore(0)
```

2. Add `filter` to your `vite-plugin-babel`
```
babel({
    filter:  /\.jsx?$/
})
```

**Comment by bekos** [comment]
@domosedov thx, your answer is very helpful 🙏 and it works! Just a note in case some reads it in the future, that for typescript you also need to add to `.babelrc` something like `@babel/preset-typescript`. Maybe this should be added to the docs. Thanks again 😃
