### ISSUE TITLE
Add .once property to Gate API 

### ISSUE THREAD

**Issue by RewriteH** [effector/effector#858]
## Proposal
It is can be useful to keep code small and simple, when you need to do something only on first Gate render

## Use case
I meet a case when i need to call something only on first gate render. Now I'm using restore for this logic:

```ts
import { createGate, restore } from 'effector-react'

const PageGate = new createGate()
const $isPageGateMountedOnce = restore(PageGate.open, false)

sample({
  clock: $isPageGateMountedOnce
  target: fetchFx
)}
```

But with the `.once` property we don't need to use restore and create another store. It keeps a code a little bit smaller than before + its very understandable for effector beginners.

```ts
import { createGate } from 'effector-react'

const PageGate = new createGate()

sample({
  clock: PageGate.once
  target: fetchFx
)}
```

**Comment by zerobias** [comment]
Looks legit 👍 But I’m concerned about naming, “once” is pretty vague definition of “on the first render only”. Could you suggest something more explicit please?

**Comment by RewriteH** [comment]
> Looks legit 👍 But I’m concerned about naming, “once” is pretty vague definition of “on the first render only”. Could you suggest something more explicit please?

onceOpened ? 😄

**Comment by alpatovdanila** [comment]
Seems like semantically such gate can be called "disposable" or "one-time(r)". Can be clunky to use in everyday code tho.

**Comment by sergeysova** [comment]
Are we really need to add `.once` property to a Gate?
Looks like we need to introduce `.once` to **each** unit in effector for consistency.

What about to solve this task via `patronum/once` operator (not exists yet)?
I think it will be much more flexible.

```ts
sample({
  clock: once(PageGate.once),
  target: fetchFx,
})
```

---

_Also, @RewriteH you don't need to `new createGate()`, use just `createGate()`_

**Comment by zerobias** [comment]
Hmm, yeah, I forgot about once in patronum

**Comment by RewriteH** [comment]
> Are we really need to add `.once` property to a Gate? Looks like we need to introduce `.once` to **each** unit in effector for consistency.
> 
> What about to solve this task via `patronum/once` operator (not exists yet)? I think it will be much more flexible.
> 
> ```ts
> sample({
>   clock: once(PageGate.once),
>   target: fetchFx,
> })
> ```
> 
> _Also, @RewriteH you don't need to `new createGate()`, use just `createGate()`_



> Are we really need to add `.once` property to a Gate? Looks like we need to introduce `.once` to **each** unit in effector for consistency.
> 
> What about to solve this task via `patronum/once` operator (not exists yet)? I think it will be much more flexible.
> 
> ```
> sample({
>   clock: once(PageGate.once),
>   target: fetchFx,
> })
> ```
> 
> _Also, @RewriteH you don't need to `new createGate()`, use just `createGate()`_

👍🏻  Looks like a very flexible solution.
Are there is mistake in your sample, with .once property in `once(PageGate.once)` and it should be .open property?

**Comment by sergeysova** [comment]
@RewriteH Yep, thank you. Fixed
