### ISSUE TITLE
Bugs in safari displaying documentation

### ISSUE THREAD

**Issue by viktorkasap** [effector/effector#860]
I don't know, maybe it's a feature and not a bug, but just in case...

![2023-02-27 12 46 00](https://user-images.githubusercontent.com/73124371/221543728-9ffb2dbe-ff92-4e1c-a771-ee06ff8187f2.jpg)

![2023-02-27 12 46 07](https://user-images.githubusercontent.com/73124371/221543718-e50e83a6-5843-4b28-b3ec-352360533098.jpg)

![2023-02-27 12 46 03](https://user-images.githubusercontent.com/73124371/221543722-6d08542b-608c-49c5-bb04-9ac95af7b19f.jpg)

![2023-02-27 12 46 10](https://user-images.githubusercontent.com/73124371/221543709-21a5bc38-e653-4b04-bd50-ac53d429e827.jpg)

**Comment by sergeysova** [comment]
I checked in Safari 18.0.1 | Arc 1.63.1 | Firefox 131.0.2.

You saw early View Transitions API support in Astro. Already disabled
