### ISSUE TITLE
Update Countdown timer recipe to use sample

### ISSUE THREAD

**Issue by KenjiTakahashi** [effector/effector#885]
https://effector.dev/docs/recipes/countdown
It's the only non-React recipe in the Docs and it's using the now "discouraged" `guard` and `forward` calls.
Perhaps worth updating?

**Comment by sergeysova** [comment]
@KenjiTakahashi The documentation is in process of update right now.
But you can contribute: https://next.effector.dev

**Comment by KenjiTakahashi** [comment]
Ah, looks like it is updated in the new docs indeed. It is fine by me then, I'd say.
