### ISSUE TITLE
`useUnit` returns stale value when used on dynamically changing Event

### ISSUE THREAD

**Issue by kireevmp** [effector/effector#900]
**What is the current behavior:**
When you change the Event provided to `useUnit` as an argument, the hook returns a stale value.

Please see the reproduction: https://share.effector.dev/jr0mXZYS

**What is the expected behavior:**
Like `useEvent`, `useUnit` should return an up-to-date value with the new callback.

**Which versions of effector packages?**
`master`, `effector v22.8.5` & `effector-react v22.5.1` at the moment of writing

**Comment by zerobias** [comment]
Fixed in effector-react 22.5.2
