### ISSUE TITLE
How to extract all Stores of Scope (including derived)

### ISSUE THREAD

**Issue by darky** [effector/effector#911]
https://share.effector.dev/OJMDESBV

I tried to extract all `Stores` of `Scope`. 
But derived not extracted (`$storePlus1`)
Only if use some dirty hack like `Scope.reg`

**Comment by zerobias** [comment]
What problem are you solving by doing this?

**Comment by darky** [comment]
I write some plugin for Node.js 
For each lifecycle (like HTTP request/handle Kafka message and so on) I'am collecting `Stores` (including derived) in `Scope` and at the end auto persistance in DB happens
Idea don't touch DB directly, just use `Store` abstraction, something like ORM over Effector

**Comment by sergeysova** [comment]
But what the reason storing derived stores in DB?

**Comment by darky** [comment]
It's Node.js application

**Comment by darky** [comment]
I abstract DB records as `Store`
Something like ORM abstract DB records as `Entity`

**Comment by sergeysova** [comment]
But derived stores is always recalculated from the original stores. I can't see the reason storing them. When you tried to restore state for original stores, derived will be recalculated at the same moment, isn't it?

**Comment by darky** [comment]
Yep derived `Store` will be recalculated at the same moment
But why no reason to persist derived `Store` in DB?
It's can be another physical `Entity`

**Comment by darky** [comment]
So, I can use internal `Scope.reg` property, it has all info about `Store` including derived
But I afraid, that `Scope.reg` signature can be changed in new versions

**Comment by Kelin2025** [comment]
```ts
const $derived = combine({ foo, bar, baz })
const $dbRecord = createStore($derived.defaultState).on($derived, (prev, next) => next)
```

**Comment by AlexandrHoroshih** [comment]
> It's can be another physical Entity

But if that entitiy is modelled as a derived store - it is a, probably, just a combination of other entities anyway? 🤔 

So in case of reading and using that state it will be recalculated anyway, so by using `serialize` there is a less overhead for serialization itself, less data in the DB to store

**Comment by darky** [comment]
> ```ts
> const $derived = combine({ foo, bar, baz })
> const $dbRecord = createStore($derived.defaultState).on($derived, (prev, next) => next)
> ```

It's good solution, thanks! I miss case, that `Store` can be used as trigger for another `Store`. But this solution propagates boilerplate. Need for every derived `Store` write one 1 line of code, which convert derived `Store` to not derived.


> > It's can be another physical Entity
> 
> But if that entitiy is modelled as a derived store - it is a, probably, just a combination of other entities anyway? 🤔
> 
> So in case of reading and using that state it will be recalculated anyway, so by using `serialize` there is a less overhead for serialization itself, less data in the DB to store

It's ok to denormalize data and have many views of same data. Some reasons:
* HDD/SDD much cheaper than CPU/RAM.
* Users very often just read data and make side effects very rare

So I want to have CPU less *reading* side, without unnecessary joins, aggregations and so on. And rich reactive *writing* side, which precalculate *reading* side. Derived `Stores` make sense in this case and will be used very often.

**Comment by Kelin2025** [comment]
> this solution propagates boilerplate

```ts
const serializableCombine = shape => {
  const $combined = combine(shape)
  return createStore($combined.defaultState).on($combined, (prev, next) => next)
}
```
Now it's `serializableCombine(shape)`, no boilerplate
I believe we don't need to solve such exotic use cases on a library-level

**Comment by darky** [comment]
Yep, I already thought about own wrappers around `combile`, `.map`, `sample` and so on.
But I don't want do it, I want using of Effector "as is" from library user POV
Ok, I will use `Scope.reg`
Thanks guys for time spending!

> I believe we don't need to solve such exotic use cases on a library-level

Yep agree. IMO Effector on Node.js application is exotic case overall :grin:
