### ISSUE TITLE
Possible Bug in Execution Queues

### ISSUE THREAD

**Issue by secundant** [effector/effector#921]
The problem can be illustrated with the following code snippet:

```typescript
const start = createEvent()

const $a = createStore(0)
const $b = createStore(0)

const refetch = createEvent()
const fetchFx = createEffect(() => null)

const $params = combine({ a: $a, b: $b })

sample({
  clock: start,
  target: refetch,
})

sample({
  clock: refetch,
  source: $params,
  target: fetchFx,
})

sample({
  clock: start,
  fn: () => 5,
  target: $a,
})

sample({
  clock: start,
  fn: () => 10,
  target: $b,
})
```

Although the flow is constructed through an intermediate event, the sequence of samples still becomes disrupted.

### Current behavior

```text
start 
     -> refetch
     -> fetchFx (called with old combined source)
     -> $a
     -> combine($a, $b)
     -> $b
     -> combine($a, $b)
 ```

![telegram-cloud-photo-size-2-5233231644188593666-y](https://github.com/effector/effector/assets/31571122/db856ed5-3e5c-433b-a76e-7770187af662)

> **Note** As seen in the screenshot, the debug indicates that "refetch" was called before the combine, while "fetchFx" was invoked afterwards but with the old combined store value.

Placing these samples before `sample({ clock: refetch, … })` appears to rectify the issue.
Here is the demo link: https://share.effector.dev/Mws8WFSE

### Expected behavior

```text
start 
     -> refetch
         -> fetchFx (called after all left statements with NEW combined source)
     -> $a
     -> combine($a, $b)
     -> $b
     -> combine($a, $b)
 ```

![telegram-cloud-photo-size-2-5233231644188593667-y](https://github.com/effector/effector/assets/31571122/a2e984e4-dc38-43cf-b6c8-276ffe07da58)

**Comment by zerobias** [comment]
All samples executed in declaration order, even if you called derived events. Use `attach` to explicitly tell effector that this effect will read the state before start

```ts
const fetchParamsFx = attach({
  source: { a: $a, b: $b },
  effect: ({a, b}) => ({a, b}),
})

sample({
  clock: start,
  target: refetch,
})

sample({
  clock: refetch,
  target: fetchParamsFx,
})
```

https://share.effector.dev/SnxNIH94
