### ISSUE TITLE
[forest] `classList`: classes in a form of `Store<string>` are not applied to element at render time

### ISSUE THREAD

**Issue by pijng** [effector/effector#964]
**What is the current behavior:**

Currently, if you specify a `Store<string>` value in `classList`, classes are not applied to the element. 
At the same time, if you manually update `Store` after rendering - classes will be applied.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via https://share.effector.dev, https://codesandbox.io or similar**

Reproduce with bug: https://share.effector.dev/leP7CAMf
Reproduce with "hack" by manually updating `Store` with classes: https://share.effector.dev/nVjf4XsB (provided by ZeroBias)

**What is the expected behavior:**

Classes specified in the `classList` in a form of `Store<string>`are applied to element at render time without the need for additional updates.

**Which versions of effector packages, and which browser and OS are affected by this issue? Did this work in previous versions of effector?:**

`"forest": "^0.21.2"`
`"effector": "^22.8.6"`

**Comment by sergeysova** [comment]
Is it kind of a duplicate of #965 ?

**Comment by pijng** [comment]
I think yes, you could consider it a dupe. 
Closing this issue in favor of #965
